- README.md
> Add the build instructions to README

- Cargo.lock
- Cargo.toml
- src/stegos.rs
> Implement basic command line argument handling

- README.md
> Fixed copyright notice

- Cargo.lock
- Cargo.toml
- config/Cargo.toml
- config/src/error.rs
- config/src/lib.rs
- config/src/types.rs
- src/consts.rs
- src/stegos.rs
- stegos.toml.example
> Add configuration infrastructure

- Cargo.lock
- Cargo.toml
- network/Cargo.toml
- network/src/lib.rs
- src/stegos.rs
This branch is based on #14 because rebasing can be complicated.
> Implement structured logging infrastructure

- .gitlab-ci.yml
- Cargo.lock
- Cargo.toml
- LICENSE
- ci-scripts/install-deps.sh
- crypto/Cargo.toml
- crypto/src/lib.rs
- crypto/src/pbc/mod.rs
- examples/pbc.rs
Resolves #76 
@dbmcclain Your code now lives in `stegos_crypto::pbc` module.
Application code (main function) moved to `examples/pbc.rs`
> Incorporated code from rust-libp2p as separate stegos_crypto::pbc module

- ci-scripts/install-deps.sh
> Run ldconfig to pick up freshly installed libraries

- Cargo.lock
- blockchain/Cargo.toml
- blockchain/src/block.rs
- blockchain/src/input.rs
- blockchain/src/output.rs
- blockchain/src/payload.rs
- crypto/src/hash/mod.rs
- crypto/src/lib.rs
- crypto/src/pbc/fast.rs
- crypto/src/pbc/secure.rs
- Add stubs for PublicKey, Signature, Payload and other
- Define Input, Output, BlockHeader and Block structures
- Implement block signature
- Implement genesis block in simplified way
Closes #32
> Implement block header

- testing/node02/stegos.toml
- testing/node03/stegos.toml
Closes #100 
All test nodes were using the same keys from node01
> Fix error in testing configuration files.

- Cargo.lock
- blockchain/Cargo.toml
- blockchain/src/lib.rs
- blockchain/src/merkle.rs
- crypto/src/hash/mod.rs
> Implement prunable Merkle Tree

- Cargo.toml
- blockchain/src/output.rs
- crypto/Cargo.toml
- crypto/src/bulletproofs/mod.rs
- crypto/src/curve1174/cpt.rs
- crypto/src/curve1174/ecpt.rs
- crypto/src/curve1174/fields.rs
- crypto/src/curve1174/fq51.rs
- crypto/src/curve1174/lev32.rs
- crypto/src/curve1174/mod.rs
- crypto/src/curve1174/u256.rs
- crypto/src/curve1174/winvec.rs
- crypto/src/pbc/mod.rs
not ready for review... just making work visible to team
> Dbm working 6

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/lib.rs
- blockchain/src/output.rs
- crypto/src/hash/mod.rs
- src/stegos.rs
> Implement a primitive in-memory UTXO database

- network/src/node.rs
We already have lock on the whole structure
> Remove locks from fields of Node structure

- Cargo.lock
- examples/ncp-ping.rs
- network/Cargo.toml
- network/protos/ncp.proto
- network/src/lib.rs
- network/src/ncp/handler.rs
- network/src/ncp/mod.rs
- network/src/ncp/protocol.rs
- network/src/node.rs
Now handle following messages:
* Ping
* Pong
* GetPeersRequest
* GetPeersResponse
> Initial complete NCP implemented

- Dockerfile
- ci-scripts/install-deps.sh
> Fix Dockerhub automated image build

- network/src/node/mod.rs
- randhound/src/lib.rs
- src/console.rs
- src/stegos.rs
> Switch to new network API

- .gitlab-ci.yml
- README.md
- ci-scripts/coverage.sh
- ci-scripts/install-deps.sh
Mostly changes to CI
Closes #83
> Added code coverage report using codecov.io

- README.md
Fixed URL for coverage badge
Added build status badge
Closes #148
> Fixed badges in README.md

- stegos.toml.example
> Fixed multiaddr literal in stefos.toml.example

- network/src/node/broker.rs
> Fixed consumers processing

- crypto/src/curve1174/cpt.rs
* implemented std::hash::Hashable
* methods to encode/decode PublicKey and Pt as Vec<u8>
> Implement utility functions for curve1174/cpt/PublicKey

- crypto/src/pbc/fast.rs
- randhound/src/randhound.rs
> Provisional implementation of Randhound++ protocol

- blockchain/src/blockchain.rs
- Refactor the code
- Add additional checks
- Remove panic!()
> Make blockchain code to be more fool-proof

- Cargo.lock
- Cargo.toml
- src/console.rs
- src/consts.rs
- src/stegos.rs
- Use linenoise(readline) for CLI
- Add prompt
- Fix arguments parser
Closes #44
> Rework CLI

- blockchain/src/merkle.rs
- crypto/src/curve1174/fields.rs
- crypto/src/curve1174/fq51.rs
- crypto/src/curve1174/mod.rs
- crypto/src/curve1174/u256.rs
- crypto/src/hash/mod.rs
- crypto/src/pbc/fast.rs
- crypto/src/pbc/mod.rs
- crypto/src/pbc/secure.rs
- crypto/src/utils/mod.rs
- network/src/node/heartbeat/mod.rs
- randhound/src/randhound.rs
> Unify into_hex()/try_from_hex() API in crypto

- crypto/src/hash/mod.rs
- network/build.rs
- network/protos/heartbeat_proto.proto
- network/src/node/heartbeat/mod.rs
- network/src/node/mod.rs
- node/build.rs
> Added signature to Heartbeat message

- randhound/src/lib.rs
Closes #211 
That's not a bug, actually. It will go away, when #208 and #209 will be completed
> Temporally disable Randhound to address #211

- node/src/lib.rs
> Add Node API to subscribe for epoch changes

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/genesis.rs
- blockchain/src/transaction.rs
- node/protos/node.proto
- node/src/lib.rs
- node/src/protos/mod.rs
- node/src/protos/node.rs
- Add bulletproofs validation
- Validate tx monetary balance explicitly (was implicit via signature)
- Validate block monetary balance
Closes #178
Closes #191
> Add monetary balance verification

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/genesis.rs
- blockchain/src/merkle.rs
- blockchain/src/output.rs
- blockchain/src/transaction.rs
- crypto/src/bulletproofs/mod.rs
- crypto/src/hash/mod.rs
- node/protos/node.proto
- node/src/lib.rs
- node/src/protos/mod.rs
- node/src/protos/node.rs
- src/console.rs
Add fee both for monetary and data transactions.
Closes #168
> Implement fee calculation

- CONTRIBUTING.md
- blockchain/src/error.rs
- blockchain/src/genesis.rs
- blockchain/src/merkle.rs
- blockchain/src/output.rs
- crypto/src/lib.rs
- network/build.rs
- network/examples/floodsub.rs
- network/src/ncp/protocol.rs
- network/src/node/heartbeat/mod.rs
- network/src/node/mod.rs
- node/build.rs
- node/src/bootstrap.rs
- node/src/lib.rs
- randhound/build.rs
No semantic changes. This patch is pure refactoring.
Follow up #184
> Reformat the code using rustfmt 1.0

- README-Testing.md
- config/src/types.rs
- create-testing-keys.sh
- network/src/node/mod.rs
- randhound/src/lib.rs
- randhound/src/randhound.rs
- start-cluster.sh
- stop-cluster.sh
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/stegos.toml.j2
* Skip waiting for timeout, if all fast keys are received
* Updated epoch
* Scripts and instructions to run N Stegos nodes
* Fix Randhound to work on large number of nodes (16+)
Closes #240 #236 #238 #244
> Many Randhound improvements

- randhound/src/lib.rs
- randhound/src/randhound.rs
Using Delay() future pollutes runtime with many unnecessary futures. Using DelayQueue is more straightforward and allows clearing delay, if all keys were received before deadline
> Replaced Delay futures with single DelayQueue for quorum deadline

- node/src/lib.rs
- randhound/src/lib.rs
- randhound/src/randhound.rs
> Use Option<> for Randomness result from Randhound

- start-cluster.sh
- testing/waiter.sh
> Don't terminate tmux, after the application termination

- Cargo.lock
- Cargo.toml
- network/Cargo.toml
- Switch to local libp2p fork
- Update dependencies
> Fix libp2p

- blockchain/src/output.rs
- blockchain/src/transaction.rs
Possible strengthening of our proof of ownership signatures on cloaked Public Keys inside UTXOs
**NOTE:
This PR is presented for review and comment. Do not commit to Dev branch yet, until implications are more fully understood and approved by group.**
> Proposed Strengthening

- blockchain/src/blockchain.rs
- consensus/src/state.rs
- keychain/src/lib.rs
- network/src/node/mod.rs
- node/src/lib.rs
- node/src/tickets.rs
- src/console.rs
- stegos-log4rs.toml.example
+ Minor renamings.
Closes #221
> Improve readability of logs

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/genesis.rs
- blockchain/src/output.rs
- blockchain/src/transaction.rs
- config/src/lib.rs
- node/protos/node.proto
- node/src/lib.rs
- node/src/protos/mod.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
Please review #338 and #342 first.
> Rename MonetaryOutput to PaymentOutput

- node/protos/node.proto
- node/src/lib.rs
- node/src/protos/mod.rs
- node/src/tickets.rs
- for now height is the same as height in blockchain (genesis block now count).
- The size of epoch is 5 block (1 keyblock, and 4 monetary).
- For now if last epoch block was received during collecting ticket, it will restart vrf ticket system imedialty. (Perviously, the error was produced, and vrf system restarts on timeout).
Closes: https://github.com/stegos/stegos/issues/309
> Add height into VRFTicket, and remove unused error.

- node/src/lib.rs
- src/console.rs
- wallet/src/change.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
> REPL commands to stake/unstake tokens

- testing/stegos.toml.j2
> Generate full meshed testing configs

- testing/stegos.toml.j2
> Exclude local node from seed nodes

- Cargo.lock
- blockchain/src/output.rs
- src/console.rs
- wallet/Cargo.toml
- wallet/src/change.rs
- wallet/src/error.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
`unstake` without arguments unstakes all of the money.
Closes #350
> Add REPL command to unstake all of the money

- node/src/lib.rs
- node/src/mempool.rs
Pure refactoring. 
Requires #372 
Needed for #300.
Needed for #217.
Needed for #304.
Closes #299
>  Decouple Mempool from NodeService

- Cargo.lock
- node/src/lib.rs
- src/console.rs
- src/stegos.rs
- txpool/Cargo.toml
- txpool/build.rs
- txpool/protos/txpool.proto
- txpool/src/api.rs
- txpool/src/lib.rs
- txpool/src/messages.rs
- txpool/src/protos.rs
Introduce basic transaction pool implementation.
Without real work with transaction.
Without real facilitator choosing algorithm.
Without real mixing.
But with real handling network event.
> Basic transaction pool Implementation.

- Cargo.lock
- network/Cargo.toml
- network/src/lib.rs
- network/src/libp2p_network/kad_discovery.rs
- network/src/libp2p_network/mod.rs
- network/src/peerstore/mod.rs
> Initial Kademlia discovery

- .gitlab-ci.yml
- Dockerfile
- ci-scripts/install-deps.sh
> Update CI to Rust 1.32 and use new library pack

- .gitlab-ci.yml
- ci-scripts/install-deps.sh
> Added macOS jobs

- Cargo.lock
- keychain/Cargo.toml
- keychain/src/lib.rs
> Removed `rand` dependency from `stegos_keychain`

- network/src/dummy_network.rs
- network/src/lib.rs
- network/src/libp2p_network/mod.rs
- node/src/lib.rs
- node/src/tickets.rs
- src/console.rs
- src/stegos.rs
- txpool/src/lib.rs
* removed generics from NetworkProvider trait
* Implemented Clone and Debug for NetworkProvider trait
> Use Box<NetworkProvider> instead of parametrization of derived structs

- network/src/dummy_network.rs
- network/src/lib.rs
- network/src/libp2p_network/mod.rs
- txpool/src/api.rs
- txpool/src/lib.rs
> Unicast protocol now provides `from` field with sender's pkey

- network/src/libp2p_network/mod.rs
- src/console.rs
* Handle case of unicast messgaes to self
* Subscribe console to unicast messages
* subscribe to unicast stream with protocol id = `console`
* display received messages
Closes #417, #418
> Fix unicast sending to itself + console send support

- blockchain/src/block.rs
- blockchain/src/escrow.rs
- blockchain/src/lib.rs
- consensus/src/multisignature.rs
- node/src/election.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/tickets.rs
Increase maximum validators hardlimit.
VRF now wait for 2/3 of stakers tickets.
Keyblock now validates min group size.
> Add minimal stakers amount.

- Dockerfile
> Fix docker build (add libmpfr4 to final image)

- blockchain/src/blockchain.rs
- consensus/src/state.rs
- node/protos/loader.proto
- node/src/lib.rs
- node/src/loader.rs
- node/src/protos/mod.rs
Closes: #319 
Closes: #320 
- Implemented basic network bootstrap.
- ConsensusMessages in one epoch from ALL future height now are silently added into queue.
> Initial bootstrap implementation.

- Cargo.lock
- crypto/src/bulletproofs/mod.rs
- crypto/src/dicemix/mod.rs
- crypto/src/hash/mod.rs
- node/src/lib.rs
- txpool/protos/txpool.proto
- txpool/src/lib.rs
- txpool/src/protos.rs
- wallet/Cargo.toml
- wallet/build.rs
- wallet/protos/valueshuffle.proto
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
- wallet/src/valueshuffle/error.rs
- wallet/src/valueshuffle/message.rs
- wallet/src/valueshuffle/mod.rs
- wallet/src/valueshuffle/protos.rs
> Add initial ValueShuffle skeleton

- serialization/src/build_script.rs
> Fix `includes` vector in case of single file input

- blockchain/src/block.rs
- crypto/src/hash/mod.rs
- node/src/protos/mod.rs
> Allow using str in `digest`, and impl Hashable for references.

- node/src/lib.rs
- node/src/tickets.rs
Call deserialization in one place, make handlers accept types.
> Split protobuf convert and buisnes logic.

- src/console.rs
- wallet/src/lib.rs
> Fix error handling in Wallet

- Cargo.lock
- blockchain/Cargo.toml
- blockchain/src/blockchain.rs
- network/Cargo.toml
- node/Cargo.toml
- node/src/lib.rs
- node/src/test/mod.rs
- node/src/test/time.rs
- node/src/tickets.rs
Now every instant is taken from tokio-timer
Closes:#456
> Implement mocking tyme system, and test timer.

- blockchain/src/block.rs
- blockchain/src/error.rs
- blockchain/src/output.rs
- blockchain/src/transaction.rs
- config/src/lib.rs
- node/src/lib.rs
- node/src/validation.rs
Extract validation code from node/src/lib.rs
No semantic changes. This patch is pure refactoring.
> Extract validation code from node/src/lib.rs

- blockchain/src/blockchain.rs
- node/src/lib.rs
- node/src/validation.rs
Fix regression introduced by f9305a78 "Extract validation code"
+ Remove non-determinism from blockchain validation code
> Fix epoch validation for sealed blocks

- .gitlab-ci.yml
- CONTRIBUTING.md
I added cargo audit step into our CONTRIBUTING.md, and into our CI pipeline.
Also in this pullrequest i changed a link of our discord channel (i found that this link was broken), to our telegram channel.
Partialy closes: #354
> Add cargo audit to our CI.

- blockchain/src/storage.rs
This is incopatile change with old dev. (You should clear database in order to test it)
Test `iter_order` breaks on dev. 
Closes: #476
> Fixed a bug in storage that collect blocks in wrong order.

- Dockerfile
> Fix stegos version in Docker image

- src/console.rs
> Fix `show utxo` output

- src/stegos.rs
> Try to load configuration file from the current directory

- node/src/loader.rs
- node/src/tickets.rs
> Fix VRF create ticket on node without stake.

- node/src/lib.rs
> Check genesis block during recovery.

- src/stegos.rs
> Don't print error on missing stegos-log4rs.toml file

- src/stegos.rs
> Configure default logging, in case of missing configuration

- .gitlab-ci.yml
> Extend  stack size for cargo test

- Cargo.lock
- Dockerfile
- ci-scripts/install-deps.sh
- crypto/build.rs
> Link external lbs (GMP, MPFR, FLINT, PBC) statically into binary

- network/Cargo.toml
- node/src/lib.rs
- node/src/test/mod.rs
- node/src/test/vrf_tickets.rs
- node/src/tickets.rs
Partially closes: #444 (only test related to persistency left)
> Tests for vrf system

- blockchain/src/blockchain.rs
Closes: https://github.com/stegos/stegos/issues/521
> Fix chain loading limit.

- src/console.rs
Value Shuffle is not ready yet.
> Comment out `spay` command

- node/src/lib.rs
- node/src/loader.rs
- src/stegos.rs
Closes: #493 
Closes: https://github.com/stegos/stegos/issues/437
Adds log info about chain loading.
Closes: #510 
Closes: #511
> Request chain just after node start.

- blockchain/src/blockchain.rs
- blockchain/src/genesis.rs
- blockchain/src/output.rs
- consensus/src/protos.rs
- keychain/src/lib.rs
- network/src/lib.rs
- network/src/libp2p_network/mod.rs
- network/src/unicast_send/behavior.rs
- node/src/lib.rs
- node/src/loader.rs
- node/src/test/simple_tests.rs
- node/src/test/vrf_tickets.rs
- node/src/tickets.rs
- node/src/validation.rs
- src/console.rs
- src/stegos.rs
- txpool/src/lib.rs
- wallet/src/api.rs
- wallet/src/lib.rs
Use "network keys" instead of "cosi keys" and "secure keys".
Closes #542
> Rename cosi keys to network keys

- blockchain/protos/blockchain.proto
- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/genesis.rs
- blockchain/src/protos.rs
- blockchain/src/storage.rs
- consensus/src/multisignature.rs
- consensus/src/protos.rs
- crypto/src/pbc/secure.rs
- node/src/election.rs
- node/src/lib.rs
- node/src/protos/mod.rs
- node/src/tickets.rs
- node/src/validation.rs
> Rename witnesses to validators

- blockchain/src/escrow.rs
One month is too long for testing.
Closes #547
> Change BONDING_TIME to 15 minutes

- Cargo.lock
- blockchain/src/merkle.rs
- blockchain/src/output.rs
- blockchain/src/transaction.rs
- crypto/Cargo.toml
- crypto/src/curve1174/cpt.rs
- crypto/src/curve1174/ecpt.rs
- crypto/src/curve1174/fields.rs
- crypto/src/curve1174/mod.rs
- crypto/src/curve1174/u256.rs
- crypto/src/dicemix/mod.rs
- crypto/src/hash/mod.rs
- crypto/src/pbc/fast.rs
- crypto/src/pbc/secure.rs
- crypto/src/protos.rs
- keychain/src/lib.rs
- network/src/libp2p_network/mod.rs
- network/src/ncp/protocol.rs
- network/src/unicast_send/protocol.rs
- node/src/lib.rs
- node/src/tickets.rs
- src/console.rs
- wallet/src/lib.rs
Zap secret key memory to zeros before deallocation
> Implement Drop trait on secret keys

- node/protos/node.proto
- node/src/protos/mod.rs
- node/src/test/vrf_tickets.rs
- node/src/tickets.rs
Closes: https://github.com/stegos/stegos/issues/533
> Add view_change to vrf ticket message.

- node/src/election.rs
- node/src/tickets.rs
Closes: https://github.com/stegos/stegos/issues/548
> Choose node with lowest hash as leader.

- network/protos/unicast_proto.proto
- network/src/libp2p_network/mod.rs
> Sign/check unicast packets, sent over the net

- network/src/libp2p_network/mod.rs
- network/src/peerstore/mod.rs
> Added floodsub message tracing

- .gitlab-ci.yml
> Remove unnecessary artifacts store and build stage

- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/storage.rs
- node/src/lib.rs
- node/src/loader.rs
- node/src/test/simple_tests.rs
- node/src/test/vrf_tickets.rs
- node/src/tickets.rs
- node/src/validation.rs
Don't store blockchain in the memory. Keep only indexes.
Blocked by #579
Closes #545
> Remove blocks from the memory

- blockchain/src/blockchain.rs
- node/src/loader.rs
block_by_hash didn't update on monetary block
Closes: #591
> Fix a bug with chain didnt load after recover.

- node/src/loader.rs
- node/src/tickets.rs
related to https://github.com/stegos/stegos/issues/440
> Request blocks from node that send future ticket.

- blockchain/src/blockchain.rs
Print correct height in the message.
> Fix "Registered xxx block" message

- blockchain/src/blockchain.rs
- node/src/lib.rs
Don't change change blockchain.validators/blockchain.leader.
Blockchain state can only be altered by register_xxx_block().
> Remove blockchain.change_group()

- blockchain/src/blockchain.rs
> Add basic tests for struct Blockchain

- .gitlab-ci.yml
> Added job to build static release binary

- blockchain/src/output.rs
- crypto/src/curve1174/cpt.rs
unencrypted UTXO with 
new_uncloaked(recipient_pkey: &PublicKey, amount: i64) -> Result<(Self, Fr)
-- returns UTXO and gamma from Bulletproof
with_uncloaked_payload(
recipient_pkey: &PublicKey,
amount: i64,
data: PaymentPayloadData,
) -> Result<(Self, Fr), Error>  -- returns UTXO and gamma from Bulletproof
Recipient pub key remains uncloaked, payload remains unencrypted, with keying hint of all zero
> produce unencrypted UTXO 

- blockchain/src/blockchain.rs
- blockchain/src/genesis.rs
- crypto/src/utils/mod.rs
- node/src/test/vrf_tickets.rs
- node/src/tickets.rs
> Fix broken dev caused by #610

- wallet/protos/valueshuffle.proto
- wallet/src/valueshuffle/error.rs
- wallet/src/valueshuffle/message.rs
- wallet/src/valueshuffle/mod.rs
- wallet/src/valueshuffle/protos.rs
cleanup, light refactoring, 
initial error traps and race conditions examined, 
first cut at uniform state handling on error returns
remove warning ignores and cleanup to standard Rust
remove unused code
> ValueShuffle Hardening

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- consensus/protos/consensus.proto
- consensus/src/blockchain.rs
- consensus/src/protos.rs
- crypto/src/hash/mod.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/test/consensus.rs
- node/src/test/simple_tests.rs
- node/src/test/vrf_tickets.rs
- node/src/validation.rs
> Remove pBFT consensus for monetary blocks

- blockchain/src/blockchain.rs
- node/src/lib.rs
- node/src/loader.rs
- node/src/test/consensus.rs
- node/src/test/mod.rs
- node/src/test/simple_tests.rs
- node/src/tickets.rs
- node/src/validation.rs
- src/stegos.rs
- Remove public members from `struct Blockchain`.
- Add getters.
- Pass genesis via constructors.
Needed for #629
> Encapsulate blockchain state

- blockchain/src/blockchain.rs
- blockchain/src/lib.rs
- blockchain/src/mvcc.rs
> Implement multi-versioned map

- network/protos/gatekeeper_proto.proto
- network/src/gatekeeper/behavior.rs
- network/src/gatekeeper/handler.rs
- network/src/gatekeeper/mod.rs
- network/src/gatekeeper/proto.rs
- network/src/gatekeeper/protocol.rs
- network/src/lib.rs
- network/src/libp2p_network/mod.rs
- network/src/libp2p_network/peer_state.rs
- network/src/ncp/behavior.rs
- network/src/ncp/mod.rs
- network/src/pubsub/behavior.rs
- network/src/pubsub/handler.rs
- network/src/pubsub/mod.rs
When connected, both ends have their PubSub and NCP protocols disabled.
After successful negotiation protocols are enabled and start operating as usual.
This a bare minimum and will be adjusted when DHT discovery and routing will be added to the mix.
Closes #635 #636
> Initial minimal implementation of nodes handshake

- network/src/gatekeeper/behavior.rs
- network/src/libp2p_network/mod.rs
> Notify top-level behavior on peers disconnect

- network/src/lib.rs
- network/src/loopback.rs
- node/src/lib.rs
- node/src/test/mod.rs
- src/stegos.rs
Closes: #564 
Test if chain can be loaded from stored genesis.
> Added chain consistency check.

- crypto/src/curve1174/fq51.rs
Incorporate new primitive gnorm(x: &Fq51, y: &mut Fq51) to normalize redundant encodings
add primitive geq(x: &Fq51, y: &Fq51) -> bool to provide faster equality comparison
removes need to convert to Fq representation before modular reduction and comparison
> Fix Fq51 Corner Cases

- blockchain/src/blockchain.rs
- blockchain/src/config.rs
- blockchain/src/election.rs
- blockchain/src/escrow.rs
- node/src/config.rs
- node/src/lib.rs
- node/src/loader.rs
- node/src/test/consensus.rs
- node/src/test/mod.rs
- node/src/test/simple_tests.rs
- node/src/tickets.rs
- node/src/validation.rs
- src/bootstrap.rs
- src/config.rs
- src/stegos.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
Move hard-coded constants to configuration files.
Closes #646
> Remove almost all hard-coded constants

- network/src/loopback.rs
- node/src/config.rs
- node/src/lib.rs
- node/src/test/consensus.rs
> Request block from last leader on timeout.

- crypto/src/curve1174/ecpt.rs
- crypto/src/curve1174/fq51.rs
perform gnorm() ahead of parity testing to remove modular excesses from redundant encodings. The alternate, excess, encodings have opposite parity.
> fix Fq51::is_odd() corner cases

- network/src/ncp/handler.rs
- network/src/pubsub/handler.rs
Errors can happed, if remote closed substream from his side sooner, than we.
So, just report and proceed with other substreams.
Closes #673
> Don't disable protocol on substream close error

- blockchain/src/blockchain.rs
- blockchain/src/config.rs
- blockchain/src/election.rs
- blockchain/src/error.rs
- blockchain/src/multisignature.rs
- consensus/src/state.rs
- node/src/config.rs
First iteration of refactor, to use validator id instead of public key.
> Refactor multisignature, to use index based.

- node/src/lib.rs
- node/src/test/mod.rs
- src/stegos.rs
Move initialization into constructor.
Fixes #698
> Remove handle_init() and network_ready() from Node

- Cargo.lock
- Cargo.toml
- api/Cargo.toml
- api/src/config.rs
- api/src/lib.rs
- src/config.rs
- src/stegos.rs
- stegos-log4rs.toml.example
- stegos.toml.example
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/stegos.toml.j2
- Add a WebSocket server based on Tokio.
See #69
> Add WebSocket API Server

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/escrow.rs
- blockchain/src/output.rs
- blockchain/src/transaction.rs
- blockchain/src/view_changes.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/test/simple_tests.rs
- node/src/validation.rs
Add block's height and block's hash to almost all messages
and errors.
Closes #536
> Refactor the log and the error messages

- .gitlab-ci.yml
> Use Rust v1.33 in CI

- blockchain/benches/election.rs
run `cargo +nightly bench -p stegos_blockchain` to see a numbers.
My results:
```
test create_vrf                  ... bench: 117,091,900 ns/iter (+/- 21,465,275)
test hash_prng_1000              ... bench:     582,190 ns/iter (+/- 44,593)
test isaac_prng_1000             ... bench:       6,869 ns/iter (+/- 44)
test select_1000_slots_out_of_16 ... bench:     658,940 ns/iter (+/- 170,905)
test verify_vrf                  ... bench: 231,142,180 ns/iter (+/- 33,345,902)
```
> Add benches of leader election

- network/src/gatekeeper/behavior.rs
- network/src/ncp/handler.rs
- network/src/pubsub/handler.rs
> Temporal fix for NodeType negotiations

- network/src/kad/addresses.rs
> Extend timer values for expiration in Kad test

- network/src/pubsub/handler.rs
> Remove unnecessary warning on substream close

- network/build.rs
- network/protos/delivery_proto.proto
- network/src/delivery/behavior.rs
- network/src/delivery/handler.rs
- network/src/delivery/metrics.rs
- network/src/delivery/mod.rs
- network/src/delivery/proto.rs
- network/src/delivery/protocol.rs
- network/src/lib.rs
- network/src/utils/expiring_queue.rs
Not yet connected to the rest of the network layer.
Part of DHT Unicast send epic.
Closes #722
> Initial delivery protocol implementation

- .gitlab-ci.yml
> Enable release build on all branches

- Dockerfile
> Use Rust v1.33 in Docker builds

- api/src/lib.rs
- src/console.rs
- wallet/src/api.rs
- wallet/src/lib.rs
- Move WalletRequest to stegos_wallet.
- Remove matching on WalletRequest from stegos_api.
Follow up #69.
> Review fixes for Wallet API

- api/src/lib.rs
Add an opaque identifier which can be used to match responses with requests.
Closes #741
> Add `id` to WalletRequest and WalletResponse

- node/src/lib.rs
- node/src/timer.rs
Move timers to separete structure, this will alow better control on timers in future.
> Split timers from node.

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/election.rs
- consensus/protos/consensus.proto
- consensus/src/error.rs
- consensus/src/lib.rs
- consensus/src/message.rs
- consensus/src/protos.rs
- consensus/src/state.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/test/consensus.rs
- node/src/validation.rs
> Implement round for keyblock consensus.

- Cargo.lock
- api/Cargo.toml
- api/src/lib.rs
- blockchain/src/blockchain.rs
- blockchain/src/election.rs
- blockchain/src/escrow.rs
- node/src/lib.rs
- src/console.rs
- src/stegos.rs
- txpool/src/lib.rs
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/valueshuffle/mod.rs
> Export Node API to WebSocket

- .gitignore
- network/src/utils/lru_bimap.rs
- network/src/utils/mod.rs
> Initial implementation of LRU Bimap

- node/src/config.rs
- node/src/loader.rs
> Speed up network synchronization procedure

- network/src/kad/kbucket.rs
> Reverse order of nodes, returned by find_closes()

- network/src/loopback.rs
- node/src/test/consensus.rs
- node/src/test/mod.rs
> Starting test implementation for consensus

- src/stegos.rs
At present, network service and metrics exporter threads are started after initialization of node_service.
Initialization of node_service takes quite some time loading data from the disk. During this time network is not active (not started) and no metrics are exported.
This patch resolves this problem.
> Start network service and metrics export first

- consensus/src/state.rs
- node/src/lib.rs
- node/src/test/consensus.rs
And adds regression tests for it.
Closes: #775 #773
> Fix bugs in consensus

- network/src/discovery/behavior.rs
- network/src/libp2p_network/mod.rs
> Update received cache for received unicast messages

- .gitlab-ci.yml
- Dockerfile
- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/protos.rs
- consensus/src/protos.rs
- wallet/src/valueshuffle/protos.rs
> Updated Rust in CI and formatting to v1.34

- node/src/mempool.rs
Since micro blocks are not validated via consensus, different
nodes may have different state of mempool. In this case it is possible
to create a situation where the same UTXO is used twice for two different
transactions on two different nodes. Of course, the only one of such
transactions will be processed and included to the block, depending on
the leader election order.
This patch removes removes from mempool all transactions which become
orphan after received a new micro block. Before this patch the usage of
the same UTXO in two different transactions caused panic of the node
Closes #755
> Allow partial pruning in mempool

- node/src/config.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/metrics.rs
Closes #45
Closes #390
Closes #468
> Limit tx, mempool and block sizes

- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/escrow.rs
- blockchain/src/output.rs
- node/src/config.rs
- node/src/lib.rs
- node/src/test/mod.rs
- node/src/test/simple_tests.rs
- node/src/validation.rs
- src/console.rs
- src/stegos.rs
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
> Rework wallet state

- network/src/gatekeeper/behavior.rs
- network/src/libp2p_network/mod.rs
- network/src/pubsub/behavior.rs
> Moved network ready detection to gatekeeper

- network/src/config.rs
- network/src/gatekeeper/behavior.rs
- src/bin/stegos.rs
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/node04/stegos.toml
- testing/stegos.toml.j2
Also, set 4 bits complexity for localhost `dev` chain
Closes #851
> Add configuration to HashCash complexity

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/protos.rs
- blockchain/src/transaction.rs
- blockchain/src/validation.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/validation.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
- wallet/src/valueshuffle/mod.rs
Simply the things and unify Transaction with MicroBlocks.
No semantic changes. This patch is pure refactoring.
See #828
> Inline TransactionBody into Transaction

- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/validation.rs
- consensus/protos/consensus.proto
- consensus/src/error.rs
- consensus/src/optimistic.rs
- consensus/src/protos.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/loader.rs
- node/src/test/microblocks.rs
If proof was received, even without block, we should rollback
> Rollback in case of view_change proof received.

- blockchain/protos/blockchain.proto
- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/protos.rs
- blockchain/src/transaction.rs
- blockchain/src/validation.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/test/simple_tests.rs
- node/src/validation.rs
- wallet/examples/show_utxo_chunks.rs
- wallet/src/lib.rs
- wallet/src/transaction.rs
- wallet/src/valueshuffle/mod.rs
Prepare for RestakeTransaction.
See #856
> Rename Transaction to PaymentTransaction, add enum Transaction

- blockchain/protos/blockchain.proto
- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/protos.rs
- blockchain/src/transaction.rs
- blockchain/src/validation.rs
- crypto/src/pbc/secure.rs
- wallet/src/transaction.rs
rebase on dev,
adopt pbc::SecretKey instead of pbc::secure::SecretKey, etc
fix comments
> RestakeTransaction added as enum variant of Transaction

- network/src/gatekeeper/behavior.rs
- network/src/libp2p_network/mod.rs
> Send Network::Ready event on subscription to status channel

- Cargo.lock
- network/Cargo.toml
- network/src/delivery/handler.rs
- network/src/delivery/protocol.rs
- network/src/gatekeeper/handler.rs
- network/src/gatekeeper/protocol.rs
- network/src/kad/behaviour.rs
- network/src/kad/handler.rs
- network/src/kad/protocol.rs
- network/src/kad/query.rs
- network/src/libp2p_network/mod.rs
- network/src/ncp/behavior.rs
- network/src/ncp/handler.rs
- network/src/ncp/protocol.rs
- network/src/pubsub/handler.rs
- network/src/pubsub/protocol.rs
> Updated to libp2p core v0.7.0

- node/src/lib.rs
Send notification to wallet after performing rollback.
Closes #840
> Fix buggy "db pop block" command

- network/protos/ncp_proto.proto
- network/src/ncp/behavior.rs
- network/src/ncp/handler.rs
- network/src/ncp/protocol.rs
- network/src/utils/expiring_queue.rs
Also, if all known peers expire, (re)connect to the seed nodes
Closes #854
> Drop stale connections

- network/src/ncp/behavior.rs
> Fix explosive outbound connects on start

- Cargo.lock
- network/src/ncp/protocol.rs
> Fix typo in NCP protobuf decode

- network/src/pubsub/behavior.rs
> Drop incoming messages from not-enabled peers

- blockchain/protos/blockchain.proto
- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/protos.rs
- blockchain/src/transaction.rs
- blockchain/src/validation.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/mempool.rs
Coinbase must be a first transaction in the block.
Closes #865
> Convert Coinbase to transaction

- network/src/gatekeeper/behavior.rs
- network/src/libp2p_network/mod.rs
Temporal workaround
Better HashCash handshake is on the way
Closes #872
> Random delay as race workaroung

- crypto/src/bulletproofs/mod.rs
- crypto/src/curve1174/ecpt.rs
initial commit via parallelized vector operations in cross-domain dot-products and others
> Speed up BulletProof Validation

- node/src/lib.rs
- node/src/test/microblocks.rs
> Fix panic after fork resolution.

- blockchain/src/blockchain.rs
Check the hash of genesis block on the start before trying to load
remaining blocks from the disk.
> Check genesis block before loading entire database

- network/src/config.rs
- network/src/gatekeeper/behavior.rs
Now network ready threshold is configured in `[network[` section of config file
> Make network readiness threshold tunable

- blockchain/src/block.rs
- blockchain/src/transaction.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/proposal.rs
- node/src/test/microblocks.rs
> Add rewards to MacroBlocks

- Cargo.lock
- network/src/gatekeeper/behavior.rs
- network/src/kad/behaviour.rs
- network/src/libp2p_network/mod.rs
- network/src/pubsub/behavior.rs
- src/bin/stegos.rs
- testing/node01/stegos.toml
... also simplified Pubsub/Gatekeeper negotiations
> Reconnect failed mutual connection attempts

- Cargo.lock
- network/Cargo.toml
- network/src/pubsub/behavior.rs
- network/src/pubsub/metrics.rs
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/node04/stegos.toml
- testing/stegos.toml.j2
As a first part of flood protection, measure incoming pubsub messages rate, and publish corresponding metrics
Closes #925
> Added incoming messages rate metric for PubSub

- network/src/pubsub/behavior.rs
> Update metrics periodically, instead of on message receive

- blockchain/src/blockchain.rs
- blockchain/src/escrow.rs
- blockchain/src/mvcc.rs
- blockchain/src/validation.rs
- node/src/lib.rs
- Rename MVCC `version` to `lsn` to avoid confusion with Block `version`.
- Move handling of InvalidViewChange from apply_micro_block() to handle_block()
- Refactor validate_micro_block()
> Prepare for new Macro Blocks

- wallet/src/lib.rs
Process EpochChanged event before OutputsChanged event.
> Fix assertion in wallet

- node/src/lib.rs
> Check block for valid primary key before starting fork resolution

- network/src/libp2p_network/mod.rs
> Detect listening address from the running Swarm

- api/src/lib.rs
- node/src/lib.rs
Replace BlockAdded with SyncChaned. Send this event on view changes too.
Closes #961
```
{
"notification": "sync_changed",
"is_synchronized": false,
"epoch": 1,
"offset": 3,
"view_change": 0,
"last_block_hash": "556610b75508de06fbede1d93c9f34428f284ea73016be263b8bc7429bcbb8b7",
"last_macro_block_hash": "2e664915cf3145c64581e8389e536c4901b4945474e86cc354fe07bae768af42",
"last_macro_block_timestamp": {
"secs_since_epoch": 1559304077,
"nanos_since_epoch": 243000000
},
"local_timestamp": {
"secs_since_epoch": 1559821128,
"nanos_since_epoch": 566407847
}
}
```
> Add notification about synchronization status to Node API

- src/bin/stegos.rs
- src/console.rs
Generator has been moved into a separate binary.
> Remove generator from console

- .gitignore
- Cargo.lock
- api/Cargo.toml
- api/src/config.rs
- api/src/crypto.rs
- api/src/error.rs
- api/src/lib.rs
- stegos.toml.example
* All messages are encrypted with AES256 encryption and encoded in base64 to transmit as WebSocket text message for easier debugging
* API key is read from file, which can be configured in config file (default: api_token.txt)
Closes #946
> Websocket API message encryption implemented

- src/bin/bootstrap.rs
> Add generated Wallet pkey output to console

- blockchain/src/blockchain.rs
- blockchain/src/error.rs
- blockchain/src/escrow.rs
- blockchain/src/slashing.rs
- blockchain/src/validation.rs
- node/src/validation.rs
- wallet/src/lib.rs
Move stake validation into one place.
This patch is pure refactoring.
> Refactor stake validation

- .gitignore
- Cargo.lock
- blockchain/src/config.rs
- clear-database.sh
- node/src/lib.rs
- src/bin/stegosd.rs
- src/bin/transaction_generator.rs
- src/config.rs
- src/console.rs
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/node04/stegos.toml
- testing/stegos.toml.j2
- wallet/Cargo.toml
- wallet/build.rs
- wallet/protos/wallet_log.proto
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/protos.rs
- wallet/src/storage.rs
- wallet/src/transaction.rs
- wallet/src/valueshuffle/protos.rs
Feature that i decide to move to separate task: 
1 Rewrite transaction interests, to use link to log, and make it recoverable after restart
1.2 Also update status of transaction on tx commit or cancel.
> Payment certificate api

- .gitlab-ci.yml
> Build release binaries for stegosd and stegos cli

- .gitignore
- api/src/lib.rs
- clear-database.sh
- src/config.rs
- src/console.rs
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/node04/stegos.toml
- testing/stegos.toml.j2
- wallet/src/api.rs
- wallet/src/lib.rs
> Refactor console

- node/src/lib.rs
- wallet/src/lib.rs
> Don't accept transactions until synchronized

- .gitignore
- clear-database.sh
- src/config.rs
- testing/node01/stegos.toml
- testing/node02/stegos.toml
- testing/node03/stegos.toml
- testing/node04/stegos.toml
- testing/stegos.toml.j2
* chain database - `data/chain`
* wallet database - `data/wallet`
Closes #1008
> Changed default locations for chain and wallet databases

- Dockerfile
> Add stegosd to Docker image

- api/src/server.rs
- start-cluster.sh
> Fix panic in API

- consensus/src/state.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/proposal.rs
- node/src/test/consensus.rs
Fixed a bug with handling of invalid proposes, that causes node to stuck on prevote state.
Fixed a bug with handling of proposes from invalid epoch, which causes node to panic.
> Add tests for invalid prevotes and proposes.

- Dockerfile
> Switched base image to pinned nightly Rust version

- crypto/src/scc/mod.rs
Adds a unit test to check for constant time SCC performance
> add test for constant time SCC verification

- crypto/src/pbc/internal.rs
- crypto/src/pbc/mod.rs
Change affects only BLS Signature Construction, not validation. Adds a random value to the secret key ahead of point multiplication, and subtracts point multiplication by cloaking factor.
This increases the time to construct a BLS signature (now about 656 usec, up from about 450 usec), but only by about 40%. No cost to BLS Signature Verify.
VRF's are not affected.
This change is mandated to avoid timing attacks on the non-constant-time PBC curve arithmetic.
> add random cloaking to secret key in BLS Construction

- blockchain/src/blockchain.rs
- node/src/lib.rs
- node/src/mempool.rs
Node should recover transaction in mempool, when some microblock is rollbacked.
> Recover transaction in case of microblock rollback.

- api/src/lib.rs
- api/src/server.rs
- blockchain/src/blockchain.rs
- node/src/api.rs
- node/src/lib.rs
- node/src/test/consensus.rs
- node/src/txpool/mod.rs
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/valueshuffle/mod.rs
Also added tx statuses to node.
> Refactor notifications to send use single channel.

- blockchain/src/blockchain.rs
- blockchain/src/config.rs
- blockchain/src/error.rs
- blockchain/src/validation.rs
- node/src/config.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/mempool.rs
- node/src/proposal.rs
> Vet timestamps in micro blocks

- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/test/account_transaction.rs
Also convert SnowballCreated to notification message.
> Make snowball return tx created response, when transaction formed.

- blockchain/src/config.rs
- node/src/config.rs
- node/src/error.rs
- node/src/lib.rs
- node/src/mempool.rs
- src/bin/stegosd.rs
Update constants for mainnet
Make [chain] and [node] to be read-only for mainnet/testnet
> Update constants for mainnet

- node/src/txpool/mod.rs
Closes: #422
For testing this pullrequest, i need to create N fake wallets. I will try to do it separately.
> Limit maximum participant in txpool.

- wallet/protos/account_log.proto
- wallet/src/protos.rs
> Fix comment field for outputs in show history.

- blockchain/src/awards.rs
- blockchain/src/blockchain.rs
> Fix service awards message duplication.

- blockchain/src/blockchain.rs
- blockchain/src/election.rs
- node/src/lib.rs
- node/src/test/integration.rs
- node/src/test/mod.rs
Closes: #943 
Adds test for slashing finalization.
Found a bug with consensus and service award integration. Have fixed in this pullrequest.
> Fix service award and consensus integration with slashing.

- wallet/src/lib.rs
- wallet/src/storage.rs
Closes: https://github.com/stegos/stegos/issues/1116
> Set transaction to committed status after macro block.

- node/src/test/futures_testing.rs
- node/src/test/mod.rs
Closes: https://github.com/stegos/stegos/issues/1120
Closes: https://github.com/stegos/stegos/issues/1121
> Fix bug in test framework that at some condition could cause to failing.

- blockchain/src/blockchain.rs
- blockchain/src/metrics.rs
- blockchain/src/timestamp.rs
- node/src/config.rs
- node/src/lib.rs
- node/src/metrics.rs
- src/lib.rs
- Use fractional seconds for all times.
- Add dozens of new metrics.
Closes #1064
> Refactor monitoring metrics

- Dockerfile
- ci-scripts/install-deps.sh
> Updated Dockerfile and external libraries

- wallet/src/lib.rs
> Fix check for leading '.' in accounts folder

- api/src/lib.rs
Check that decrypted buffer has starting '{' and trainling '}'.
```
2019-07-18 11:20:37,724 ERROR [stegos_api] Failed to parse JSON: msg={"account_id":"1","type":"keys_info","account_address":"7fYkji6pAUmwLwtkDQnXEy5We6qHTQpRxmxEia4aXs6Cv4C4taF","network_address":"9cd35a3c09172c2890394351a865c0053b8d45be55b2f30bfaadfedd2c6f23e6e15f911d7aab1e1035bcb687d0fec60967f3beb635974ccd7b5956cd05008892c16f9bb6fe127f94606770666cdb9ebf17376dc9eab2a7ceb8085ff4400f9496"}, error=data did not match any variant of untagged enum ResponseKind at line 1 column 322
2019-07-18 11:20:37,724 ERROR [stegos_api::client] [ws://0.0.0.0:3145] RequestError("Failed to parse JSON")
```
Closes #1099
> Don't log binary data on decryption error in API

- api/src/lib.rs
- api/src/server.rs
- src/bin/stegosd.rs
- src/console.rs
> Show remote server version on `show version`

- blockchain/src/metrics.rs
- blockchain/src/validation.rs
- crypto/src/pbc/mod.rs
- node/src/lib.rs
- node/src/metrics.rs
> Tune monitoring histograms

- .gitlab-ci.yml
> Ignore fast-checks temporary.

- wallet/src/lib.rs
- wallet/src/test/account_transaction.rs
> Wait until recovery ends before processing requests in AccountService

- node/src/api.rs
- node/src/lib.rs
- wallet/src/lib.rs
- wallet/src/protos.rs
- wallet/src/storage.rs
- wallet/src/test/account_transaction.rs
Also rename status "Prepare" to "Prepared", for consistency
> Fix resending tx on timeout.

- blockchain/src/blockchain.rs
- blockchain/src/test.rs
- wallet/src/lib.rs
- wallet/src/storage.rs
- wallet/src/test/account_transaction.rs
Closes: #1147 
Add utxo to log, if it was didn't known before.
> Make wallet log recover after unseal correctly.

- crypto/src/vdf/mod.rs
Fixes VDF to prevent predictable proofs when Challenge in [0, 1]. Uses XOR by 2, instead of XOR by 1.
> Fix Predictable Buterin VDFs

- wallet/protos/snowball.proto
- wallet/src/snowball/message.rs
- wallet/src/snowball/mod.rs
- wallet/src/snowball/protos.rs
- wallet/src/test/account_transaction.rs
Remove this incomplete feature in order to re-add it later.
> Remove VsRestart from Snowball

- network/src/ncp/behavior.rs
> Filter out discovered localhost IPs

- .gitlab-ci.yml
> Automatically build binaries on `dev` branch

- blockchain/src/escrow.rs
- blockchain/src/output.rs
- src/bin/stegos/console.rs
- wallet/protos/account_log.proto
- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/protos.rs
- wallet/src/snowball/message.rs
- wallet/src/storage.rs
- wallet/src/test/account_transaction.rs
- wallet/src/transaction.rs
Closes: https://github.com/stegos/stegos/issues/1180
> Refactor wallet structures.

- crypto/src/dicemix/mod.rs
- wallet/src/snowball/mod.rs
remove pending_removals, as it is never used
add debug message for pending_participants remaining pending on timeout
> Snowball Cleanup - Part 2

- network/src/discovery/behavior.rs
- network/src/ncp/behavior.rs
> Fix Unicast delivery

- src/bin/stegos/main.rs
- src/bin/stegosd/main.rs
Supported variables for `stegos`:
- STEGOS_API_ENDPOINT
- STEGOS_API_TOKEN_FILE
- STEGOS_DATA_DIR -- used only to find api.token
Supported variables for `stegosd`:
- STEGOS_API_ENDPOINT
- STEGOS_PROMETHEUS_ENDPOINT
- STEGOS_DATA_DIR
- STEGOS_CONFIG
- STEGOS_LOG_CONFIG
- STEGOS_CHAIN
Closes #2142
> Allow to override almost all configuration options via environment

- network/src/ncp/behavior.rs
- testing/node01/stegosd.toml
- testing/node02/stegosd.toml
- testing/node03/stegosd.toml
- testing/node04/stegosd.toml
- testing/node05/stegosd.toml
- testing/node06/stegosd.toml
- testing/node07/stegosd.toml
- testing/stegosd.toml.j2
Renam `public_endpoint` to `advertised_endpoint`.
> Follow up network configuration refactoring

- .gitignore
- network/src/libp2p_network/mod.rs
- network/src/pubsub/behavior.rs
> Disable `Pubsub` forwarding, if node has no public address

- wallet/protos/snowball.proto
- wallet/src/snowball/message.rs
- wallet/src/snowball/mod.rs
- wallet/src/snowball/protos.rs
- could happen if participants disagree on commit_phase_participants
> Fix Snowball matrix size mismatch

- node/src/api.rs
- node/src/lib.rs
- src/bin/stegos/console.rs
Allow user to enable/disable automatic restaking.
> Add `enable restaking` / `disable restaking` commands

- Cargo.lock
- Cargo.toml
- api/src/client.rs
- src/bin/stegos/console.rs
- src/bin/stegos/main.rs
```
echo -e "show balance\nshow keys\n" | stegos
---
- type: balance_info
...
---
- account_id: "1"
type: balance_info
balance: yyy
available_balance: xxx
...
---
- type: keys_info
...
---
- account_id: "1"
type: keys_info
account_address: yyy
network_address: xxx
...
```
> Make CLI suitable for scripting

- src/bin/stegos/console.rs
- wallet/src/api.rs
- wallet/src/error.rs
- wallet/src/lib.rs
Also fixes a problem duplicate accounts.
Closes #1237
Closes #1244
> Add public keys to `show accounts`

- src/bin/stegos/console.rs
- Fix amount parser for `stake` command.
- Fix "unstake " with space.
- Don't commands starting with a space to the history.
Fixes #1265
Fixes #524
> Fix CLI parser

- network/protos/dht.proto
- network/protos/ncp_proto.proto
- network/protos/pubsub_proto.proto
- network/protos/unicast_proto.proto
- network/src/kad/protocol.rs
Use the same version of Protobuf in all modules.
> Switch to protobuf3 in network

- wallet/src/lib.rs
> Block api on unseal.

- ci-scripts/Dockerfile
- ci-scripts/build.sh
Support old distros too. Also fixes buggy PATH in build.sh
> Downgrade CI image to ubuntu:xenial

- wallet/src/api.rs
- wallet/src/lib.rs
- wallet/src/metrics.rs
- wallet/src/test/account_transaction.rs
```
{
"account_id": "1",
"type": "balance_info",
"payment": {
"current": 999883208000000,
"available": 999883208000000
},
"public_payment": {
"current": 45384000000,
"available": 45384000000
},
"stake": {
"current": 50000000000,
"available": 0
},
"current": 999978592000000,
"available": 999928592000000
}
```
> Add information about Payment, Stake, PublicPayment balances

- wallet/src/error.rs
- wallet/src/lib.rs
- wallet/src/storage.rs
- wallet/src/test/account_transaction.rs
- wallet/src/transaction.rs
Closes: https://github.com/stegos/stegos/issues/1276
Closes: https://github.com/stegos/stegos/issues/1272
Closes: https://github.com/stegos/stegos/issues/1273
> Fix unstake bug.

- wallet/src/api.rs
- wallet/src/lib.rs
> Track final status of balance change notification.

- crypto/src/dicemix/mod.rs
- wallet/src/snowball/mod.rs
It's requested replacement of https://github.com/stegos/stegos/pull/1274 but without handwritten serialization.
> Add framing in snowball and limit size of utxo.

- clear-database.sh
- crypto/src/scc/mod.rs
- src/bin/stegos/console.rs
- wallet/protos/account_log.proto
- wallet/src/api.rs
- wallet/src/error.rs
- wallet/src/lib.rs
- wallet/src/protos.rs
- wallet/src/storage.rs
- wallet/src/test/account_transaction.rs
- wallet/src/transaction.rs
Needed for exchange integration.
> Implement Bitcoin-like public addresses - WIP

- blockchain/src/blockchain.rs
before choosing leader.
Also change dificulty to 10.
> Save award info at end of past epoch

- src/bin/bootstrap.rs
> Use warning instead of error for stakes < min_stake_amount

- blockchain/src/block.rs
- blockchain/src/blockchain.rs
- node/src/lib.rs
- node/src/test/mod.rs
- wallet/src/lib.rs
- wallet/src/snowball/mod.rs
- Handle Async::Ready(None) properly.
- Add description to all unreachable!() calls.
> Fix handling of EOF in all Tokio streams

- Cargo.lock
- network/src/libp2p_network/mod.rs
> Update version of our for of resolver.

- wallet/src/lib.rs
Scan blockchain from the beginning.
> Fix balances after 24-word recovery

- wallet/src/api.rs
- wallet/src/lib.rs
Nobody will unseal account before deleting. Unseal it automaticaly
> Allow deleting of sealed account.

- wallet/src/lib.rs
- wallet/src/storage.rs
Fix timestamps in history after recovery.
Set timestamp to time from block, instead of local time
> Fix timestamp in logs after recovery.

- network/src/config.rs
- network/src/libp2p_network/mod.rs
- src/bin/stegosd/main.rs
Also add traces of resolver error.
Also add posibility to override dns.
> Fix AAA record resolving.

- network/src/pubsub/behavior.rs
* Ensure entries expiration in LRU cache
* Set expiration time for PubSub LRU to 4.5 minutes
> Fix PubSub LRU cache

- blockchain/src/protos.rs
Follow up bfadbd7e "Fix deserialization of BitVec"
> Trim traling zeros for multisigmap in ViewChangeProof

- node/src/replication/peer.rs
Follow up 3038f39 "entered unreachable code"
> Fix unreachable!() in replication/src/peer.rs

- Cargo.lock
- blockchain/Cargo.toml
- blockchain/src/blockchain.rs
- ci-scripts/build.sh
- wallet/Cargo.toml
- wallet/src/storage.rs
Blocked until, #1375 will be merged
Also need to update branch in rocksdb dependencies
> Update rocksdb version

- blockchain/src/transaction.rs
- node/src/lib.rs
> Handle restake transaction even when not synchronized.

- blockchain/src/blockchain.rs
- blockchain/src/config.rs
- node/src/test/mod.rs
- node/src/validation.rs
- src/bin/stegosd/config.rs
- src/bin/stegosd/main.rs
- stegosd.toml.example
- testing/node01/stegosd.toml
- testing/node02/stegosd.toml
- testing/node03/stegosd.toml
- testing/node04/stegosd.toml
- testing/node05/stegosd.toml
- testing/node06/stegosd.toml
- testing/node07/stegosd.toml
- testing/stegosd.toml.j2
Replaced also in config, but in CLI keeped force_check flag
> Replace force_check flag by enum.

- ci-scripts/Dockerfile
Otherwise, about 500Mb unused stuff left behind.
> Remove /usr/src/build after all deps are installed

- blockchain/src/blockchain.rs
- blockchain/src/config.rs
- blockchain/src/test.rs
- node/src/test/integration.rs
- node/src/test/mod.rs
- src/bin/stegosd/main.rs
Add tests for service award state.
Improve test of bitvec, for bigger collections.
> Fix service award bug.

- src/bin/stegosd/main.rs
> Add chain name sufix, to data_dir, if data_dir was not set.
