crypto/src/hash/mod.rs

Follow std::hash approach for hashing.
Now it possible to define hashing logging for any struct:
// Define some structure
struct Data {
a: String,
b: u8,
c: u32,
}
// Define custom hashing logging
impl Hashable for Data {
fn hash(&self, state: &mut Hasher) {
self.a.hash(state);
self.b.hash(state);
self.c.hash(state);
}
}
// Calculate the hash
let mut hasher = Hasher::new();
d.hash(&mut hasher);
let h2: Hash = hasher.result();
My initial version re-used std::hash::Hash and std::hash::Hasher.
Unfortunally, this approach has failed completely. Rust's
std::hash has some special logic for handling built-in types.
For example, for String they call hash(str.as_bytes()) + hash(255).
It is probably needed to workaround hashing of empty strings.
The same problem happens with arrays. I want the …

Implement Rust-style hashing using SHA3-256

---

Cargo.lock
blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/genesis.rs
blockchain/src/payload.rs
crypto/Cargo.toml
crypto/src/bulletproofs/mod.rs
crypto/src/curve1174/cpt.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/lev32.rs
crypto/src/curve1174/mod.rs
crypto/src/curve1174/u256.rs
crypto/src/hash/mod.rs
crypto/src/lib.rs
crypto/src/pbc/fast.rs
crypto/src/pbc/mod.rs
crypto/src/pbc/secure.rs
examples/curve1174.rs

All modules now use the ThreadRng thread-local PRNG, which is (according to docs) a crypto-safe PRNG, seeded from entropy
create function Hash::from_hash_facsimile_str() to allow importing hash values from constant strings
Hash::from_str() is solely for the purpose of hashing arbitrary strings, akin to Hash::from_vector() for u8 vectors.
get things running unit tests properly again...

clean up PRNG usage.

---

blockchain/src/genesis.rs
crypto/src/curve1174/mod.rs
crypto/src/hash/mod.rs
crypto/src/keying/mod.rs
crypto/src/lib.rs
crypto/src/pbc/fast.rs
crypto/src/pbc/mod.rs
crypto/src/pbc/secure.rs
examples/curve1174.rs
examples/pbc.rs

patch up to use from_hex()
make PBC abide by synthetic_random for choosing keys
add unit test to verify that PRNG is not being re-init on each call to functions that use thread_rng()
Add keying module to crypto lib - this will handle conversions to/from keys and wordlists
Add wordlist to/from bignum support

change name to from_hex()

---

config/src/types.rs
network/src/ncp/handler.rs
network/src/ncp/protocol.rs
network/src/node.rs
src/stegos.rs
testing/node01/stegos.toml
testing/node03/stegos.toml

* when floodsub connection is established, both ends query each other for known peers
* each 15 seconds (configurable) check number of active floodsub connections, if that number is below configured threshold, iterate over peer store and:
* if peer is connected - request known peers
* If peer is disconnected - establish floodsub connection
Also, added infomative message to stdout, during node startup\

Initial implementation for connection monitoring

---

.gitlab-ci.yml
Cargo.lock
Cargo.toml
network/Cargo.toml
network/src/ncp/protocol.rs
src/stegos.rs

* sample test with logging is located in `src/stegos.rs` file
* we still need to add `--nocapture` to see log output
FIxes #135

Example of `log` usage with unit tests

---

crypto/src/pbc/secure.rs

Implemented .into_bytes()/.from_bytes for pbc::secure::{G2, PublicKey}

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/genesis.rs
blockchain/src/lib.rs
blockchain/src/transaction.rs
config/src/lib.rs
crypto/src/bulletproofs/mod.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/mod.rs
crypto/src/hash/mod.rs
crypto/src/pbc/fast.rs
crypto/src/pbc/mod.rs
crypto/src/pbc/secure.rs
network/src/lib.rs
network/src/ncp/protocol.rs
src/stegos.rs

Prepare for Rust 2018 Edition. No semantic changes.

Use the new syntax to import local submodules

---

blockchain/src/output.rs
crypto/src/bulletproofs/mod.rs
crypto/src/curve1174/cpt.rs
crypto/src/curve1174/ecpt.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/fq51.rs
crypto/src/curve1174/lev32.rs
crypto/src/curve1174/mod.rs
crypto/src/curve1174/u256.rs
crypto/src/curve1174/winvec.rs
crypto/src/hash/mod.rs
crypto/src/lib.rs
crypto/src/pbc/fast.rs
crypto/src/pbc/mod.rs
crypto/src/pbc/secure.rs
crypto/src/utils/mod.rs
keychain/src/lib.rs
src/console.rs

- Refactor Pt and PublicKeys constructors to forbin invalid points
- Unify into()/from() API for Pt, ECp, PublicKey, Fq, Fr, SecretKey
- Move PublicKey::cloak() into blockchain::Output as requested by David
Closes #157

Forbid invalid Pt and PublicKeys

---

start-cluster.sh
stop-cluster.sh

Run `start-cluster.sh` to start 3-node cluster.
Nodes will be running in `tmux` sessions named `node1`, `node2` and `node3`
Run `stop-cluster.sh` to terminate all nodes.

Added scripts to start/stop 3-node blockchain on localhost

---

blockchain/src/block.rs
blockchain/src/merkle.rs
node/src/lib.rs

- Send block over network
- Listen for block requests
- Track current leader and epoch
- Fix double-spending for transactions queued in mempool
Closes #48

Process sealed block

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/genesis.rs
blockchain/src/merkle.rs
blockchain/src/output.rs
blockchain/src/transaction.rs
crypto/src/hash/mod.rs
node/protos/node.proto
node/src/lib.rs
node/src/protos/mod.rs
node/src/protos/node.rs
src/console.rs

- Split Output into MonetaryOutput and DataOutput
- Allow empty merkle tree and blocks without outputs
- Add "msg" command to CLI
Other changes:
- Fix error handling in CLI
- Print epoch changing notifications in CLI
Closes #165

Implement data UTXO

---

Cargo.lock
node/Cargo.toml
node/src/lib.rs

Merge all event streams into one in order to simplify the code.
Re-use pattern introduced by 3e35c24d "Initial RandHound bootstrap"
Needed to introduce more network streams for #47

Refactor NodeService::poll()

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/genesis.rs
blockchain/src/output.rs
network/src/node/broker.rs
node/src/bootstrap.rs
node/src/lib.rs
src/stegos.rs

- Pass genesis blocks to node's constructor explicitly
- Don't include extra MONETARY_FEE for data transactions
- Add basic unit tests for NodeService
- Allow to specify the total number of coins in bootstrap utility
- Use usize instead of u64 for DATA_UNIT
- Improve debug output in Broker
- Remove NodeService::outbox (an artifact)
See #190

Add unit tests for blockchain node

---

randhound/src/randhound.rs

On the leader, send_randomness_to_leader mutates internal state, which afterwards was overwritten by stash_decrypted_shares

Fix one-off error in SubGroupRandomness collection

---

randhound/src/randhound.rs

In previous fix, I was discarding calculated values after collecting BFT of randomness
Now, values are stored in internal state, as it was in original code
Closes #276

Store decrypted shares, even when randmoness was calculated

---

crypto/examples/pbc.rs
crypto/src/pbc/mod.rs
crypto/src/pbc/secure.rs

tests would not run from cargo, so I put the test at the end of examples/pbc.rs - runs just fine
pub struct pbc::secure::VRF;
pub fun  pbc::secure::make_VRF(&pbc::secure::SecretKey, &Hash) -> pbc::secure::VRF;
pub fun pbc::secure::validate_VRF_randomness(&pbc::secure::VRF) -> bool;
pub fun pbc::secure::validate_VRF_source(&pbc::secure::VRF, &pbc::secure:PublicKey, &Hash) -> bool;

Implement VRF in module pbc::secure

---

consensus/src/message.rs
consensus/src/state.rs
node/protos/node.proto
node/src/lib.rs
node/src/protos/mod.rs

Duplicate of https://github.com/stegos/stegos/pull/325 (it was originally merged into other branch)
Closes #312
1) Now keyblock is first block in new epoch, rather then last block in old.
2) Introduce a epoch check in consensus, and push messages from future epoch into queue.

Fix async consensus behaviour

---

node/src/lib.rs

Closes: https://github.com/stegos/stegos/issues/317
Add timestamp check to consensus propose.
We still need somehow handle timestamp of sealed block, but this should be a part of fork resolution.
And we need https://github.com/stegos/stegos/issues/273 to fully test this pull-request

Check timestamp of block in block proposal.

---

Cargo.lock
blockchain/src/lib.rs
config/src/lib.rs
crypto/Cargo.toml
crypto/src/lib.rs
keychain/src/lib.rs
network/src/lib.rs
src/stegos.rs

Along the way fixed our `rust-libpbc` crate, which was causing linking issues
Closes #344

Removed unused imports

---

Cargo.lock
blockchain/src/output.rs
wallet/Cargo.toml
wallet/src/error.rs
wallet/src/lib.rs
wallet/src/transaction.rs

This patch changes transaction formation logic for `unstake` REPL command.
Before this patch `1 x PAYMENT_FEE` was charged OVER the amount specified
by `unstake` command in REPL.
With this patch `1 x PAYMENT_FEE` is charged FROM the amount specified
by `unstake` command in REPL.
Let's take look on an example. Assume that 100 tokens have been staked
into the escrow using the single UTXO.
Before this patch:
* `unstake 100` raised an error, because it actually required
`100 + PAYMENT_FEE` in the escrow.
* `unstake 100 - PAYMENT_FEE` withdrew `100 - PAYMENT_FEE`.
* `unstake 20` withdrew `20` and staked `80 - PAYMENT_FEE - ESCROW_FEE`
back to the escrow.
With this patch:
* `unstake 100` withdraw `100 - PAYMENT_FEE`.
* `unstake 20` withdraw `20 - PAYMENT_FEE` and stake `80 - ESCROW_FEE`
back to …

Change transaction formation logic for unstaking

---

node/protos/node.proto
node/src/consensus.rs
node/src/lib.rs
node/src/protos/mod.rs

Before this patch transaction was validated twice:
1. In handle_transaction() before accepting into the mempool.
2. In process_mempool() before creating a new block.
Initial idea was that transaction can be received out of order,
therefore handle_transaction() should only perform basic checks,
whereas process_mempool() should peform the full check of inputs.
Actually, we can't check anything without having resolved inputs.
Even signature can't be checked without inputs. For this reason
transactions from the future can't be checked at all. Let's ignore
out-of-order transactions for now and focus on security.
This patch integrates all checks into handle_transaction().
Mempool now contains only fully validated transactions. Nothing can
fail during creation of a block. For security reason …

Refactor transaction validation

---

serialization/src/build_script.rs

Allow single file as protobuf source in `build_protobuf`

---

keychain/src/lib.rs
src/console.rs
wallet/src/api.rs
wallet/src/lib.rs

- Add `show version` to display current version.
- Add `show balance` to display actual balance.
- Add `show utxo` to display unspent outputs.
- Add `show keys` to display keys.
- Rename `send` to `net send`.
- Rename `publish` to `net publish`.
- Remove `connect`.
- Improve readline's thread parking/unparking.
- Use Self:: instead of ConsoleService::
Closes #305
Closes #306

Add new REPL commands

---

blockchain/src/blockchain.rs
blockchain/src/escrow.rs
blockchain/src/genesis.rs
blockchain/src/output.rs
blockchain/src/protos.rs
blockchain/src/transaction.rs
node/src/bootstrap.rs
node/src/lib.rs
node/src/mempool.rs
node/src/test/simple_tests.rs
node/src/validation.rs
wallet/src/lib.rs
wallet/src/transaction.rs

- Add test cases for transaction validation.
- Refactor payload encoding/decoding for StakeUTXO.
- Use Hash::digest(&tx) instead of Hash::digest(&tx.body) as
a transaction identifier in mempool.
Closes #391

Add test cases for transaction validation

---

blockchain/src/transaction.rs
crypto/protos/crypto.proto
crypto/src/curve1174/cpt.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/mod.rs
crypto/src/dicemix/mod.rs
crypto/src/lib.rs
crypto/src/protos.rs
node/src/mempool.rs
node/src/validation.rs

- Upgrade Transactions to support TXINs to multiple payee pubkeys,
all belonging to one node who knows the corresponding secret keys.
- Added crypto primitive curve1174::cpt::sign_hash_with_kval() to support
construction of Schnorr multi-signatures.
- Add operators + and += for SchnorrSig to support multi-signatures.
- Corrections to Schnorr multi-signature construction.
- Shorten keying hint in UTXO EncryptedPayload to use only
hint = alpha * P, key = H(s * alpha * G).
Saves 32 bytes (256 bits) from every UTXO
Closes #328

Implement super-transactions for ValueShuffle

---

crypto/src/curve1174/ecpt.rs

This small change speeds up comparison of ECp points by a considerable margin, from 5 microseconds down to 335 nanoseconds, by avoiding an expensive divide operation to convert the 51-bit representation into Fq field representations. We remain in the 51-bit representation here.

speed up ECp compare from 5 microsec to 0.33 microsec

---

Cargo.lock
crypto/src/pbc/secure.rs
node/Cargo.toml
node/src/lib.rs
node/src/tickets.rs
src/console.rs
src/stegos.rs

Added api to request info from Node.
For now it just contain a field that is used to render election state, but later could be replaced by enum:
```rust
pub struct InfoNotification {
/// simple text output.
pub display: tickets::DisplayState,
}
```
But later it can be Enum that agregate other information.
The output text looks like:
```console
---
- height: 2
view_change: 0
state: sleeping
timeout: 0min 0s 247ms
collected_tickets: ~
```
For collecting phase it's not friendly, but still usable:
```console
stegos> show election
---
- height: 2
view_change: 1
state: collecting
timeout: 0min 59s 541ms
collected_tickets:
96f5dbc0ced2...: 6b93cd7a8f51a4...
```

Implement console command to show election status.

---

blockchain/src/merkle.rs
blockchain/src/output.rs
consensus/src/state.rs
crypto/examples/pbc.rs
crypto/src/bulletproofs/mod.rs
crypto/src/curve1174/cpt.rs
crypto/src/curve1174/ecpt.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/fq51.rs
crypto/src/curve1174/mod.rs
crypto/src/hash/mod.rs
crypto/src/pbc/fast.rs
crypto/src/pbc/secure.rs
keychain/src/lib.rs
network/src/unicast_send/behavior.rs
node/src/lib.rs
node/src/loader.rs
node/src/tickets.rs
node/src/validation.rs
txpool/src/lib.rs
wallet/src/transaction.rs
wallet/src/valueshuffle/mod.rs

Remove redurant Display implementation.
Removed Display implementation for SecretKeys.
Modifyed all found logs, to use `Display` in `info!` and `Debug` in `debug!`
Closes: #566

Make `Display` print shorter public keys.

---

crypto/examples/bruteforce.rs

Example code in stegos_crypto to provide timing estimates on brute force recovery of amounts from Bulletproof Pedersen commitments. 
This serves as a template for future code that can help recipients recover correct amounts when they detect a cheating UTXO where the encrypted amount differs from what had been used in the Bulletproof.
My timing estimates show that 28 bits can be recovered in about 90 sec.

Test brute force

---

Cargo.lock
Cargo.toml
build.rs
src/console.rs
src/stegos.rs

- Parse `git describe --long` output to generate version:
v0.1-49-g895818f => major=0, minor=1, patch=49, commit=895818f
- Remove `vergen` crate.
Closes #571 
Example:
```
$ git describe --long
v0.1-50-g3dbe666
$ cargo run -- --version
Finished dev [optimized + debuginfo] target(s) in 0.74s
Running `target/debug/stegos --version`
Stegos 0.1.50 (3dbe666 2019-03-06)
$ touch test
$ git add test
$ git commit -m "test"
[rt-issue-571-vergen 87f429a] test
1 file changed, 0 insertions(+), 0 deletions(-)
create mode 100644 test
$ git describe --long
v0.1-51-g87f429a
$ cargo run -- --version
Compiling stegos v0.1.0 (/home/roman/Stegos/Source/stegos)
Finished dev [optimized + debuginfo] target(s) in 17.52s
Running `target/debug/stegos --version`
Stegos 0.1.51 (87f429a 2019-03-06)
```

Use `git describe` to generate application version

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/error.rs
blockchain/src/genesis.rs
blockchain/src/multisignature.rs
node/src/error.rs
node/src/lib.rs
node/src/mempool.rs
node/src/test/simple_tests.rs
node/src/validation.rs

- Merge key_block.validate(), node.validate_sealed_key_block() and
validation checks from chain.register_key_block() into one method.
- Merge monetary_block.validate(), node.validate_sealed_monetary_block() and
validation checks from chain.register_monegtary_block() into one method.
- Remove double validation of monetary blocks.
- Remove validation of blocks during recovery.
- Add leader's signature into block's proposals.
- Validate that block's proposals always have leader's signature.
- Fix a bug that loaded blocks from the disk were written back to the disk.
This patch disables tests for block.validate() code. These tests
will be ported to the new codebase by #394.
Closes #537
Needed for #394
Needed for #539

Refactor block validation code

---

network/src/libp2p_network/mod.rs

Closes #587 
Removes log messages with Unknown topics from logs

Don't try process uniicast messages as broadcasts

---

blockchain/src/transaction.rs

No longer includes transaction signature in hash of transaction records

no longer includes transaction signature in hash

---

network/src/config.rs

- Use bind_port = 0 to allow multiple nodes on the same host.
- Disable advertise_local_ips by default.
Closes #438

Change default values for NetworkConfig

---

Cargo.lock
README-Testing.md
blockchain/src/transaction.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/mod.rs
crypto/src/dicemix/mod.rs
src/console.rs
txpool/Cargo.toml
txpool/build.rs
txpool/protos/txpool.proto
txpool/src/lib.rs
txpool/src/messages.rs
txpool/src/protos.rs
wallet/Cargo.toml
wallet/examples/show_utxo_chunks.rs
wallet/protos/valueshuffle.proto
wallet/src/error.rs
wallet/src/lib.rs
wallet/src/transaction.rs
wallet/src/valueshuffle/error.rs
wallet/src/valueshuffle/message.rs
wallet/src/valueshuffle/mod.rs
wallet/src/valueshuffle/protos.rs

Upgrade Transactions to support TXINs to multiple payee pubkeys, all belonging to one node who knows the corresponding secret keys.
provisional code for super-transactions, but needs more work
completed Transaction support for skeletal super-transaction construction
added crypto primitive curve1174::cpt::sign_hash_with_kval() to support construction of Schnorr multi-signatures
add operators + and += for SchnorrSig to support multi-signatures
corrections to Schnorr multi-signature construction
implement general purpose fee cloaked anonymous sharing to accumulate to total_fee, just like participant gamma_adj values.
fixup DiceMix dc_reconstruct() to expect two running cloaked sums (gamma_adj, and fee)
add Bulletproof verification to blame discovery checking
add garbage UTXO messages …

ValueShuffle - PoC

---

blockchain/src/blockchain.rs
blockchain/src/multisignature.rs
consensus/src/blockchain.rs
crypto/src/pbc/secure.rs
node/src/lib.rs
node/src/metrics.rs
node/src/test/consensus.rs
node/src/test/loopback.rs
node/src/test/mod.rs
node/src/test/simple_tests.rs
node/src/test/vrf_tickets.rs
node/src/tickets.rs
node/src/validation.rs

Commit proposed block with 2/3 pre-commits automatically if leader hasn't done it on time.
+ Add basic tests for consensus.
Closes #539
I don't like the part of code related to multisignature. This patch tries to augment a multisignature returned by consensus with leader's signature from proposal.

Auto-commit proposed block with 2/3 signatures on timeout

---

blockchain/src/blockchain.rs
crypto/src/pbc/secure.rs
node/src/lib.rs
node/src/test/simple_tests.rs
node/src/validation.rs
txpool/src/lib.rs
wallet/src/valueshuffle/mod.rs

- Group fields.
- Unify output_by_hash()/outputs_by_hashes() API.
- Move timestamp creation to node.
- Update comments.
- Refactor recovery.
- Add secure::PublicKey::dum() constructor.
- Other minor fixes.
No semantic changes. This patch is pure refactoring.
See #629

Refactor stegos_blockchain

---

blockchain/src/blockchain.rs
blockchain/src/escrow.rs
blockchain/src/metrics.rs
blockchain/src/mvcc.rs
blockchain/src/storage.rs

Add a new method to `struct Blockchain` called pop_monetary_block().
This method can be use to roll back all changes caused by previous
call of push_monetary_block(). Only monetary blocks can be reverted.
Every key block finalizes the state of blockchain database and cleans
the undo log for previous monetary blocks.
+ Add basic tests cases for persistency.
Closes #629

Implement the rollback operation for monetary blocks

---

node/src/lib.rs
node/src/metrics.rs

Subj.
For now if no monetary block was received for specific timeout, metrics will increased.

Add metrics for lost monetary blocks.

---

crypto/src/pbc/secure.rs
network/protos/unicast_proto.proto
network/src/libp2p_network/mod.rs

* now we both sign outgoing messages with sender key and encrypt with
recipient key
* helper functions to encode/decode pbc::secure::RVal values
Closes #671

Added encryption to unicast send

---

crypto/protos/crypto.proto
crypto/src/hashcash/mod.rs
crypto/src/lib.rs
crypto/src/protos.rs

Hashcash implements a (more or less) tunable delay function by having provers find an index that, together with some seed value, produce a hash value with an indicated number of prefix bits of zero.
hashcash::delay(nbits: usize, seed: &Vec<u8>) -> Proof
hashcash::check_proof(proof: &Proof, nbits: usize) -> bool
struct Proof {
nbits: usize,
seed: Vec<u8>,
count: i64,
}

Hashcash delay() and check_proof()

---

Cargo.lock
network/Cargo.toml
network/build.rs
network/protos/dht.proto
network/protos/ncp_proto.proto
network/src/discovery/behavior.rs
network/src/discovery/mod.rs
network/src/kad/addresses.rs
network/src/kad/behaviour.rs
network/src/kad/dht_proto.rs
network/src/kad/handler.rs
network/src/kad/kbucket.rs
network/src/kad/metrics.rs
network/src/kad/mod.rs
network/src/kad/protocol.rs
network/src/kad/query.rs
network/src/lib.rs
network/src/libp2p_network/mod.rs
network/src/ncp/behavior.rs
network/src/ncp/protocol.rs
network/src/utils/mod.rs
network/src/utils/multihash.rs

* re-worked original libp2p Kadelia implementation to work with pbc::secure::PublicKeys as node windows
* used SHA3-512 as internal hash for DHT keys
* implemented DHT-based network discovery
This is rough initial iplementation and needs more work on stability improvement and code cleanup, but it lets
us proceed to actuall message routing

Stegos Kademlia (fork of libp2p-kad)

---

blockchain/src/blockchain.rs
node/protos/loader.proto
node/src/config.rs
node/src/lib.rs
node/src/loader.rs
node/src/metrics.rs
node/src/protos/mod.rs

- Add synchronization status tracking to Node based on timestamps in the key blocks.
- Invoke loader on a view change for the key && monetary blocks.
- Throttle loader to 60/5 = 12 requests per minute.
- Limit the number of blocks in loader's response to blocks_per_epoch.
- Add a stub for the fork resolution.
- Remove a queue of orphan blocks.
Closes #687

Rework synchronization logic

---

network/src/pubsub/handler.rs

Occasionally on busy nodes timeout could happen on establishing outbound substream connection. Instead of disabling substream, just report the issue and retry later

Fix pubsub 'protocol disabled' errors

---

Cargo.lock
network/src/discovery/behavior.rs
network/src/kad/behaviour.rs
network/src/lib.rs
network/src/libp2p_network/mod.rs

On startup, get from Kademlia 10 nodes closest to outselves and maintain
open connections to them.
Part of DHT Unicast Epic
Closes #699

Establish and monitor connections to 10 closest nodes

---

network/src/libp2p_network/mod.rs
network/src/pubsub/behavior.rs

Once network considers its ready to propagate blockchain messages through the network, it sends
NETWORK_READY_TOKEN via NETWORK_STATUS_TOPIC channels

Send NETWORK_READY_TOKEN once network is up

---

Cargo.lock
Cargo.toml
consensus/src/state.rs
node/src/mempool.rs
src/config.rs
src/console.rs
src/generator.rs
src/stegos.rs
wallet/src/lib.rs

This pullrequest add transaction generator possibility to stegos node.
To start generator one can simply adds line
```
generate_txs = ["84a7e8b14b66b4567fce12b5589a93f2f6ed4404e86f3adb148ca981fb6c7a54"]
```
to `[general]` config section.
This line will activate generator to `84a7e8b14b66b4567fce12b5589a93f2f6ed4404e86f3adb148ca981fb6c7a54`
Generator will choose random key from `generate_txs` field, and create transaction for it.
One transaction at a time.
For cli usage, one can use `generator` command, with `stop` and `start` subcommands.
To add more key use `generator start NEW_KEY,NEW_KEY2`

Add generator tx implementation

---

Cargo.lock
crypto/src/hashcash/mod.rs
network/protos/gatekeeper_proto.proto
network/src/delivery/behavior.rs
network/src/gatekeeper/behavior.rs
network/src/gatekeeper/handler.rs
network/src/gatekeeper/mod.rs
network/src/gatekeeper/protocol.rs
network/src/libp2p_network/mod.rs
network/src/ncp/behavior.rs
network/src/ncp/handler.rs
network/src/ncp/mod.rs
network/src/pubsub/behavior.rs
network/src/pubsub/handler.rs
network/src/utils/expiring_queue.rs
network/src/utils/peer_id_key.rs

Now all pubsub connections are protected by "Hashcash" PoW handshake.
Initially, on all established connection, pubsub is disabled, and all attempts to send messages are blocked. To enable communications, originating node sends UnlockRequest message with optional _proof_ field. Remote node checks its list of already generated Puzzles, and if it already has puzzle for originating peer and UnlockRequest contains valid proof, then PubSub communications are enabled over this connection. Otherwise, new Puzzle is generated and sent to the originating node. Originating node than solves received Puzzle and re-attempts UnlockRequest with proper proof. If solution is correct, communications are enabled, otherwise, new Puzzle is generated and proccess repeats, until correct solution is provided. …

Hashcash integration is complete

---

crypto/src/curve1174/cpt.rs

`aes::ctr` expects key slice matching in size declared KeySize. Under rare conditions, mismatching size causes panics.
Closes #804

Fixes test failures in CI builds running in Mojave Virtualbox VM

---

blockchain/src/blockchain.rs
blockchain/src/config.rs
blockchain/src/escrow.rs
blockchain/src/output.rs
node/src/config.rs
node/src/lib.rs
node/src/validation.rs

- Replace `bonding_time` with `valid_until_epoch`.
- Rename EscrowInfo[x].total to `active_stake` and `expired_stake`.
- Rename EscrowInfo[x].stakes[y].bonding_timestamp to `valid_until_epoch`.
- Add EscrowInfo[x].stakes[y].is_active.
- Remove unused methods from `struct Escrow`.
- Update all tests.
This patch is breaking change.
Needed for #800

Lock stakes by epochs

---

blockchain/src/blockchain.rs
blockchain/src/config.rs
blockchain/src/election.rs
blockchain/src/error.rs
blockchain/src/escrow.rs
blockchain/src/output.rs
node/src/config.rs
node/src/test/consensus.rs
node/src/validation.rs
src/console.rs
wallet/src/api.rs
wallet/src/error.rs
wallet/src/lib.rs
wallet/src/transaction.rs

- Re-stake expiring stakes automatically.
- Do don't take expired stakes into account during group formation.
- Add API method and CLI command to force re-staking.
- Rework stake locking to check only for minimal staking balance
instead of locking of individiual UTXOs.
Closes #800

Implement re-staking without re-keying

---

crypto/src/curve1174/cpt.rs

Use decompression then recompress to canonical form. Then bitwise comparison.
This method was chosen because DiceMix needs a pseudo ordering of Public Keys and Pts

Fix Pt::Ord() 

---

network/src/discovery/behavior.rs
network/src/gatekeeper/behavior.rs
network/src/kad/behaviour.rs
network/src/kad/kbucket.rs
network/src/lib.rs
network/src/libp2p_network/mod.rs
network/src/loopback.rs
network/src/ncp/behavior.rs

Now `NetworkProvider` has additional function:
```
fn change_network_keys(&self, _new_pkey: secure::PublicKey, _new_skey: secure::SecretKey) -> Result<(), Error>;
```
SecretKey is necessary, because we encrypt/decrypt Unicast messages

Add API call to change Network(PBC) key

---

network/src/pubsub/behavior.rs

We need to send this event in case of both outgoing and incoming connections reach the threshold
Closes #845

Fix Network readiness status event

---

network/src/gatekeeper/behavior.rs
network/src/lib.rs
node/src/lib.rs
node/src/test/mod.rs

Fix a race on start - don't send the key && micro blocks and
the view changes until network is ready.
Closes #759

Don't send network messages until network is ready

---

blockchain/src/blockchain.rs

Blockchain::recovery_wallet() passed incorrect value of epoch to wallet.
Closes #873

Fix thread 'tokio-runtime-worker-1' panicked at 'Have stakes'

---

crypto/src/curve1174/cpt.rs
crypto/src/curve1174/fields.rs
crypto/src/curve1174/u256.rs

WAU is contagious in the result when any operand in a field arithmetic expression has WAU. Hence the u-value of the signature would be serialized using AONT encryption. 
This is not necessary in the u-value of a SchnorrSig, since by addition of two secret values from the field, the sum effectively cloaks each other's secrecy contribution. There is no need to cloak any secrecy in the u-value.
Implement a clear_wau() primitive in the field and its underlying U256 representation, to signal that serialization can proceed without AONT encryption, and add explicit clear_wau() after constructing the signature u-value.

Add clear_wau() to support SchnorrSig

---

Cargo.lock
network/src/delivery/behavior.rs
network/src/delivery/handler.rs
network/src/discovery/behavior.rs
network/src/gatekeeper/behavior.rs
network/src/gatekeeper/handler.rs
network/src/kad/behaviour.rs
network/src/kad/handler.rs
network/src/lib.rs
network/src/libp2p_network/mod.rs
network/src/ncp/behavior.rs
network/src/ncp/handler.rs
network/src/pubsub/behavior.rs
network/src/pubsub/handler.rs

* now filter incoming/outgoing events on `NetworkBehaviour` levels for PubSub
* removed `shutdown` logic from protocols (we can use Terminate NCP method to drop connections
* (refactoring) `PeerId` implements `Display` trait, so no need for explicit `.to_base58()` call

Simplified pubsub and minor updates to handlers

---

node/src/test/microblocks.rs

Leader after rollback can be a new leader again, so ignore second block of that leader.

Fix random failed test.

---

blockchain/protos/blockchain.proto
blockchain/src/block.rs
blockchain/src/genesis.rs
blockchain/src/protos.rs
blockchain/src/validation.rs

MacroBlock is signed by consensus. No ViewChangeProof is needed.
It wasn't used, just an artificat of MicroBlock->MacroBlock refactoring.
Needed for new MacroBlocks.

Remove ViewChangeProof from MacroBlock

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/transaction.rs
blockchain/src/validation.rs
node/src/error.rs
node/src/lib.rs
node/src/proposal.rs
node/src/test/microblocks.rs

Remove double validation of MacroBlockProposal
Validators try to re-create proposed MacroBlock and check that created MacroBlock has the same hash as proposed. Don't spent time validating inputs and outputs of re-created MacroBlock on blockchains because they already have been validated before.
Needed for new MacroBlocks.
- Inline validate_macro_block_payments() into validate_macro_block()

Refactor macro block validation

---

src/console.rs
wallet/src/api.rs
wallet/src/lib.rs
wallet/src/transaction.rs

- Command "cloak" allows to exchange all PublicPaymentOutput's to regular PaymentOutput's
- Add "/public" mode to "pay" command, if "/public" flag was seted create PublicPaymentOutput

Add public outputs to wallet, add command for cli.

---

node/src/lib.rs
wallet/src/lib.rs

After first restaking node counts UTXOs from epoch, as Outputs from epoch+1.
This behaviour cause restaking mechanism to work incorrectly.

Fixed a bug in restaking.

---

blockchain/src/blockchain.rs
blockchain/src/config.rs
node/src/config.rs
node/src/lib.rs
node/src/loader.rs
node/src/mempool.rs
node/src/proposal.rs
node/src/test/consensus.rs
node/src/test/microblocks.rs
node/src/test/mod.rs
node/src/test/requests.rs
node/src/validation.rs
src/bin/bootstrap.rs
src/bin/stegos.rs
src/bin/transaction_generator.rs
src/config.rs

Refactor configuration
- Separate BlockchainConfig from ChainConfig.
- Rename ChainConfig to NodeConfig.
- Rename BlockchainConfig to ChainConfig.
Tune blockchain constants
Closes #667

Refactor and tune configuration

---

Cargo.lock
crypto/Cargo.toml
crypto/src/curve1174/cpt.rs
crypto/src/lib.rs
src/bin/stegos.rs
src/console.rs
wallet/src/lib.rs

Closes #785 
* removed `to_hex/from_hex` from `curve1174::cpt::PublicKey`
* implemented trait FromStr for `curve1174::cpt::PublicKey`
* implemented trait `From<&curve1174::cpt::PublicKey> for String

Replaced hex encodings for Wallet PKey with Base58Check

---

start-cluster.sh

after https://github.com/stegos/stegos/pull/988 
./start-cluster script didn't work.
This fixes issue, by changing name of binary that started in cluster.

Fix start cluster command.

---

node/src/config.rs
node/src/lib.rs
node/src/mempool.rs
src/bin/stegosd.rs
src/bin/transaction_generator.rs
src/console.rs
src/generator.rs
wallet/src/api.rs
wallet/src/lib.rs

- Add support for `payment_fee` in API.
- Allow user to specify fee in Console.
- Sort mempool transactions by fee.

Add support for variable tx fees

---

Dockerfile

Use `/usr/local/bin/stegosd` as ENTRYPOINT (was `/usr/local/bin/stegos` which is now binary for CLI)
Closes #1010

Fix ENTRYPOINT in Dockerfile

---

node/src/loader.rs

All epochs expect the last one have only macro blocks.
Don't multiply loader_speed_in_epoch on the number of micro blocks
in the epoch.

Fix loader_speed_in_epoch

---

blockchain/src/blockchain.rs
node/src/lib.rs

- Pass current timestamp to push_micro_block()/push_macro_block().
- Refactor register_block() helper to avoid ambiguity.
Follow up #1082

Fix validation of vetted timestamp

---

wallet/src/error.rs
wallet/src/lib.rs

Closes: #985
current output:
```
---
- type: cloak_all
payment_fee: 1000
...
---
- type: error
error: No unspent public outputs was found.
```

Fix bug in API that return incorrect error for "cloak" command.

---

consensus/src/state.rs

Closes: #904 
For now, if our monitoring is fast enough, we should get real graphics of state transitions.
At least it updates correct;y.

Clear consensus state when consensus is not active.

---

node/src/lib.rs
node/src/txpool/mod.rs
src/bin/stegosd.rs
wallet/src/change.rs
wallet/src/lib.rs
wallet/src/test/mod.rs
wallet/src/transaction.rs

Also, tries to fill up inputs with smallest UTXOs to burn 'em.
Closes #1113

Limit number of input UTXOs in composed transactions

---

blockchain/src/validation.rs

The locked timestamp is already validated in micro blocks.
Add this extra check just for sure.
Closes #1006
I will test all corner cases as part of #394

Check locked_timestamp() in validate_macro_block()

---

blockchain/src/blockchain.rs
node/src/config.rs
node/src/lib.rs
node/src/mempool.rs

- Fix mistyped max_outputs_in_mempool limit.
- Skip stakes which are already in mempool during re-staking.
- Don't restake if not is node synchronized.
- Allow RestakeTransaction even if mempool is full.
- Add loggings of inputs/outputs to transactions and blocks.
Closes #1064

Fix crash on second re-staking

---

blockchain/src/awards.rs
blockchain/src/lib.rs
blockchain/src/validation.rs
node/src/test/integration.rs
node/src/test/mod.rs

Closes: https://github.com/stegos/stegos/issues/944
Assert that service awards preserve epoch statuses.
Also fix bug in macro_block validation. Which checks state according to current epoch stat, rather then according to block information.

Add tests for service award.

---

network/src/loopback.rs
wallet/src/storage.rs
wallet/src/test/account_transaction.rs
wallet/src/test/mod.rs

1. Get recovery key using api.
2. Recover from disk should save transactions.
3. Transaction should has status `Committed` on epoch change.
4. Check possibility of creating certificates, and using them to access encrypted payload.
5. Check that public payments work, and we can see amount.
6. Create transaction with invalid request produce errors: negative amount, amount more than balance, invalid comment length.
Also fix a bug in wallet, that disallow creating payment transaction with only one output.

Add more tests for wallet

---

api/src/server.rs
node/src/lib.rs
src/bin/stegos.rs
src/bin/stegosd.rs
src/config.rs
src/console.rs
src/lib.rs
testing/node01/stegos.toml
testing/node02/stegos.toml
testing/node03/stegos.toml
testing/node04/stegos.toml
testing/node05/stegos.toml
testing/node06/stegos.toml
testing/node07/stegos.toml

stegosd:
- Add `--data-dir`, `--api-endpoint`, `--prometheus-endpoint`,
`--log-config`, `--verbose`, '--force-check'.
- Allow to override the default log level via '-v', '-vv', '-vvv'.
- Don't read `stegos-log4s.toml` from the current directory by default.
- Rename `general.log4rs_config` to `general.log_config`.
stegos:
- Remove `ws://` prefix from --api-endpoint in Stegos CLI.
- Allow to override default log level via '-v', '-vv', '-vvv'.
- Don't print node notifications unless Debug level is enabled.
Needed for Stegos Wallet UI.

Allow to override configuration options via command-line

---

blockchain/src/output.rs
wallet/protos/account_log.proto
wallet/src/api.rs
wallet/src/lib.rs
wallet/src/protos.rs
wallet/src/storage.rs

Closes: https://github.com/stegos/stegos/issues/1154
1) PaymentTransactionValue now contain amount, of token that was sent.
2) LogEntry::Incoming and LogEntry::Outgoing now has tag as saperate field and has lowercase.
3) comment in OutputValue now serialized as field name, and in lowercase (data field was removed).
4) OutputValue tag now serialized as value of field `output_type`.
Example of current representation:
```
- type: outgoing
timestamp: "2019-07-24T14:04:49.598637648Z"
tx:
tx_hash: 4f5c615218eba250dc28d042d83c1804061f2c432172bfd1f78da8e33aaa3a54
amount: 4
status: committed
epoch: 1
- type: incoming
timestamp: "2019-07-24T14:08:29.452600221Z"
output:
output_type: payment
utxo: 03bf9dd22b26c8131fbf4491be776617196e4ade86b9461d8bae980bac5587dc
amount: 24000000
comment: Block …
```

Refactor serialization representation of PaymentTransactionValue and OutputValue.

---

Cargo.lock
blockchain/Cargo.toml
blockchain/src/blockchain.rs
blockchain/src/output.rs
crypto/src/scc/mod.rs
node/src/api.rs
node/src/lib.rs
src/console.rs
wallet/src/test/account_transaction.rs

- Add chain.historic_output_by_hash().
- Refactor output.validate_certificate().
- Add NodeRequest::ValidateCertificate.
- Add "validate certificate" command to CLI.
Create a transaction using `payment` API with set  `with_certificate`:
To create certificate use `with_certificate = true" in API or /certificate in CLI:
**Console:**
```yaml
pay 7fVEggZSzjHtZ6aV7EDExuvJHZJ8Q3rrSivPmdJVFaNVt1CRsEs 1 /certificate
```
**Request:**
```yaml
---
- type: payment
recipient: 7fVEggZSzjHtZ6aV7EDExuvJHZJ8Q3rrSivPmdJVFaNVt1CRsEs
amount: 1
payment_fee: 1000
comment: ""
locked_timestamp: ~
with_certificate: true
...
```
**Response:**
```yaml
---
- account_id: "1"
type: transaction_created
tx_hash: 0a3e1c48c335b43b887f559f265cbc54f69a31dea646ef7f714c1bd3edcfc3f1
fee: 2000
outputs:
- utxo: …
```

Add Payment Certificate validation

---

blockchain/src/blockchain.rs
blockchain/src/output.rs
node/src/api.rs
node/src/lib.rs
src/console.rs
wallet/src/test/account_transaction.rs

- Remove `amount from ValidateCertificate request.
- Add `amount`, `epoch`, `block_hash`, `timestamp`, `is_final` to
CertofocateValid response.
Request:
```yaml
---
- type: validate_certificate
utxo: 5e9f51f94ad2084e75708a310a6988f3b523b3623deedfe45a69c17d489524c4
spender: 7eLHNiyS6qssNNLrskYrV3G7Yade1xdtNQ5HXxao4xXXA1gx5po
recipient: 7fVEggZSzjHtZ6aV7EDExuvJHZJ8Q3rrSivPmdJVFaNVt1CRsEs
rvalue: 0db753d6aba2c0ca26ddfe3b52cd1443e1170086dde24cc34371a651b4867dfa
...
```
Response:
```yaml
---
- type: certificate_valid
epoch: 57
block_hash: d8c0646f76c854601078b1bfaeb6fa69d9cc93d92ae4e425a86abefc1c320438
is_final: true
timestamp: "2019-07-25T14:09:18.519078288Z"
amount: 1
...
```

Update ValidateCertificate API

---

wallet/src/api.rs
wallet/src/lib.rs
wallet/src/metrics.rs
wallet/src/test/account_transaction.rs
wallet/src/valueshuffle/mod.rs

Now VS can result in 3 ways:
* SignedTransaction(tx, leader) - the same it was before
* UnsignedTransaction(tx) - transaction formed, but not all signatures were collected
* Failure(Error) - fatal failure during protocol run
Also, added `terminate` method to VS, to reset its state and stop further participation in current session (if any)
Closes #1092

ValueShuffle enhancement

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
blockchain/src/validation.rs
node/src/api.rs
node/src/lib.rs
node/src/mempool.rs
node/src/validation.rs
wallet/src/lib.rs
wallet/src/test/account_transaction.rs

Keep all inputs and outputs in the block even overlapping.

Disable compaction of inputs/outputs during Macro Block creation

---

node/src/config.rs

Fixes ValueShuffle with more than 5 participants.

Increase max_outputs_in_tx to 50

---

crypto/src/dicemix/mod.rs

fixup expected colums count in matrices in DIceMix decode, to account for active + missing participants

Fix DiceMix for missing participants in Decode

---

crypto/src/dicemix/mod.rs
wallet/src/valueshuffle/mod.rs

DiceMix decode() was incorrect in its use of missing participant cloaking factors. Wrong type of HashMap was being expected.

Fix DiceMix Decode

---

crypto/src/dicemix/mod.rs
crypto/src/scc/mod.rs
wallet/protos/valueshuffle.proto
wallet/src/valueshuffle/message.rs
wallet/src/valueshuffle/mod.rs
wallet/src/valueshuffle/protos.rs

- should not enter dc_decode when number of participants falls below expected number from earlier matrix construction
It is apparent that checking self.pending_participants is not sufficient to ensure that original number of participants remain. So we were calling DiceMix::dc_decode() with inconsistent numbers of matrices when there had been drop out participants. Not all dropouts were tallied by self.pending_participants. 
(Perhaps participants who supplied invalid messages were also removed from pending_participants?) 
This patch to ValueShuffle should prevent a large number of panics that have been experienced recently. No material change to DiceMix (just some test code at the bottom, and removed yesterday's patch to count MIA's). This time if DiceMix panics then something is seriously …

fix ValueShuffle 

---

wallet/src/error.rs
wallet/src/lib.rs
wallet/src/test/account_transaction.rs
wallet/src/valueshuffle/error.rs
wallet/src/valueshuffle/mod.rs

- Convert ValueShufle to oneshot Future.
- Remove wallet_tx_info and queue_transaction();
- Fix handling of non-fatal errors.
- Remove try_xxx() wrappers.
- Move FacilitatorChanged handling to AccountService.

Refactor ValueShuffle

---

node/src/api.rs
node/src/lib.rs
node/src/txpool/mod.rs
wallet/src/lib.rs

This hack was needed to notify AccountService and TransactionPoolService
about current facilitator on the start. Patch NodeService to call TxPool
directly on init(). Patch NodeService to include information about
facilitator to AccountRecovered message for AccountService.

Don't send dummy NewMacroBlock notification on the start

---

crypto/src/dicemix/mod.rs
network/src/libp2p_network/mod.rs
wallet/src/snowball/error.rs
wallet/src/snowball/message.rs
wallet/src/snowball/mod.rs

use std::mem::replace() where appropriate
rename some structure slots to better indicate purpose
remove unused or redundant dictionaries
Rebase on latest dev branch, absorbing Vladimir's changes from this morning
other formatting changes, courtesy of newer Rust cargo fmt.
fix up the message handling to become consistent and correct
for possible arrivals from participants who are ahead of us.
Revert to simplified SID checking.
abbrev output for SnowballPayload

clean up message handling and phase dispatch

---

crypto/src/scc/mod.rs
wallet/src/snowball/error.rs
wallet/src/snowball/mod.rs

- Merge PoolState and MessageState into one enum.
- Remove timer_context.
- Remove future_facilitator.
- Use timer for PoolWait.
- Improve logging.

Streamline Snowball state machine

---

network/src/config.rs
src/bin/stegosd/main.rs

Use Cloudflare DNS servers to discover and resolve blockchain seed nodes, can be changed in configuration file.
Fixes issues with misconfigured DNS resolver
Closes #992

Fix for issues with misconfigured DNS

---

Cargo.lock
Cargo.toml
src/bin/stegos/console.rs
src/bin/stegos/main.rs

Add -f/--formatter option to CLI to choose between `yaml` and `json`
formatters.

Support JSON formatting in CLI

---

ci-scripts/build.sh

nightly ARM64 does not have
does not affect production build

patch around possibly missing rustfmt

---

src/bin/stegosd/main.rs

Also, don't apply default awards difficuly, if chain config was changed
Closes #1341

Changed default `min_stake_amount` for non-mainnet chains

---

src/bin/bootstrap.rs

Now key is validated before actual use
Closes #1345

Removed beneficiary key validation from clap

---

wallet/src/lib.rs

In #169124212 we requested to also add pending utxo status, but it already exist in as pending_timestamp

Don't show that balance is final, if some utxo is pending.

---

blockchain/src/api.rs
blockchain/src/block.rs
blockchain/src/lib.rs
blockchain/src/output.rs

```
type: macro_block_committed
block_hash: 3b9960ed9261dad6999ef68c6573881440bd7613c65f47862ef10c1c75f691bb
version: 1
previous: 685cf62751cef607271ed7190b6a707405c5b07ec0830156e748c0c2ea4a2cfe
epoch: 0
view_change: 0
...
multisigmap: "1111"
inputs: []
outputs:
- output_hash: 63ac8c606bb8368813f0f66cc1d3116e514364c9565bdc4278228f6470161d94
type: payment_output
recipient: dev1lpqygstjur8kmw6d4xmh3mpz9cjszj5kqwfujsenjc3r4ae7xsfqt8yn9s
cloaking_hint: 70c1d2a251bc3c9ba2b8a61085582bb923821d68ec7cb60e5abd17421f20224a
proof:
```

Append hash on serializing block and utxo in serde.

---

network/src/pubsub/behavior.rs

Don't refresh message time, if duplicate message was received.
Allow for re-submitted transactions

Fix LRU expiration

---

blockchain/src/block.rs
blockchain/src/blockchain.rs
node/src/lib.rs
node/src/test/integration.rs

Patch is cherry picked for previous testnet.

Introduce block cache.
